/**
 * US cities organized by state abbreviation → county name → city names array.
 * Served via /api/cities endpoint to keep the client bundle small.
 */

export const US_CITIES = {
  AL: {
    "Autauga": ["Prattville", "Autaugaville", "Billingsley", "Booth", "Jones", "Pine Level"],
    "Baldwin": ["Bay Minette", "Daphne", "Fairhope", "Foley", "Gulf Shores", "Loxley", "Orange Beach", "Robertsdale", "Silverhill", "Spanish Fort", "Summerdale"],
    "Barbour": ["Clayton", "Clio", "Eufaula", "Louisville"],
    "Bibb": ["Brent", "Centreville", "West Blocton", "Woodstock"],
    "Blount": ["Oneonta", "Cleveland", "Locust Fork", "Snead", "Susan Moore"],
    "Bullock": ["Union Springs"],
    "Butler": ["Greenville", "Georgiana", "McKenzie"],
    "Calhoun": ["Anniston", "Jacksonville", "Oxford", "Piedmont", "Weaver", "Hobson City", "Ohatchee"],
    "Chambers": ["LaFayette", "Lanett", "Valley"],
    "Cherokee": ["Centre", "Cedar Bluff", "Collinsville", "Gaylesville", "Leesburg"],
    "Chilton": ["Clanton", "Thorsby", "Jemison", "Maplesville"],
    "Coffee": ["Enterprise", "Elba", "New Brockton"],
    "Colbert": ["Tuscumbia", "Muscle Shoals", "Sheffield"],
    "Cullman": ["Cullman", "Good Hope", "Hanceville", "Holly Pond", "Vinemont"],
    "Dale": ["Daleville", "Ozark", "Fort Novosel"],
    "Dallas": ["Selma", "Orrville"],
    "DeKalb": ["Fort Payne", "Rainsville", "Collinsville", "Crossville", "Fyffe", "Geraldine", "Henagar", "Ider", "Mentone", "Sylvania"],
    "Elmore": ["Wetumpka", "Millbrook", "Eclectic", "Tallassee"],
    "Escambia": ["Atmore", "Brewton", "East Brewton", "Flomaton"],
    "Etowah": ["Gadsden", "Attalla", "Glencoe", "Hokes Bluff", "Rainbow City", "Sardis City", "Southside"],
    "Franklin": ["Russellville", "Red Bay", "Phil Campbell"],
    "Geneva": ["Geneva", "Hartford", "Samson", "Slocomb"],
    "Houston": ["Dothan", "Ashford", "Columbia", "Cowarts", "Kinsey", "Webb"],
    "Jackson": ["Scottsboro", "Bridgeport", "Stevenson", "Section", "Pisgah"],
    "Jefferson": ["Birmingham", "Bessemer", "Homewood", "Hoover", "Mountain Brook", "Vestavia Hills", "Irondale", "Trussville", "Gardendale", "Center Point", "Fultondale", "Hueytown", "Leeds", "Midfield", "Pleasant Grove", "Tarrant"],
    "Lauderdale": ["Florence", "Killen", "Rogersville", "Waterloo", "Anderson", "Lexington"],
    "Lawrence": ["Moulton", "Town Creek", "Courtland", "Hillsboro"],
    "Lee": ["Auburn", "Opelika", "Phenix City", "Smiths Station", "Beauregard"],
    "Limestone": ["Athens", "Ardmore", "Elkmont", "Lester", "Mooresville"],
    "Madison": ["Huntsville", "Madison", "New Hope", "Owens Cross Roads", "Triana", "Harvest"],
    "Marengo": ["Demopolis", "Linden"],
    "Marion": ["Hamilton", "Winfield", "Guin", "Hackleburg"],
    "Marshall": ["Albertville", "Arab", "Boaz", "Guntersville", "Grant"],
    "Mobile": ["Mobile", "Prichard", "Saraland", "Chickasaw", "Citronelle", "Satsuma", "Semmes", "Theodore"],
    "Monroe": ["Monroeville", "Frisco City"],
    "Montgomery": ["Montgomery", "Pike Road", "Millbrook"],
    "Morgan": ["Decatur", "Hartselle", "Somerville", "Priceville", "Trinity", "Falkville"],
    "Perry": ["Marion"],
    "Pike": ["Troy", "Brundidge"],
    "Randolph": ["Roanoke", "Wedowee"],
    "Russell": ["Phenix City", "Hurtsboro", "Seale"],
    "Shelby": ["Alabaster", "Pelham", "Helena", "Calera", "Chelsea", "Columbiana", "Harpersville", "Montevallo", "Vincent", "Wilsonville"],
    "St. Clair": ["Pell City", "Moody", "Springville", "Ashville", "Ragland", "Riverside"],
    "Talladega": ["Talladega", "Sylacauga", "Lincoln", "Childersburg", "Munford"],
    "Tallapoosa": ["Alexander City", "Dadeville", "Camp Hill"],
    "Tuscaloosa": ["Tuscaloosa", "Northport", "Holt", "Brookwood", "Coaling", "Coker", "Lake View", "Moundville", "Vance"],
    "Walker": ["Jasper", "Carbon Hill", "Cordova", "Dora", "Parrish", "Sumiton"],
    "Winston": ["Double Springs", "Addison", "Haleyville", "Lynn"]
  },
  AK: {
    "Anchorage": ["Anchorage", "Eagle River", "Girdwood", "Chugiak"],
    "Fairbanks North Star": ["Fairbanks", "North Pole", "Eielson AFB", "Fort Wainwright"],
    "Juneau": ["Juneau", "Auke Bay", "Douglas"],
    "Kenai Peninsula": ["Kenai", "Soldotna", "Homer", "Seward", "Sterling", "Nikiski"],
    "Ketchikan Gateway": ["Ketchikan", "Saxman"],
    "Kodiak Island": ["Kodiak"],
    "Matanuska-Susitna": ["Palmer", "Wasilla", "Big Lake", "Houston", "Talkeetna"],
    "Sitka": ["Sitka"],
    "Valdez-Cordova": ["Valdez", "Cordova"],
    "Bethel": ["Bethel"],
    "Nome": ["Nome"],
    "North Slope": ["Barrow", "Utqiagvik"]
  },
  AZ: {
    "Apache": ["St. Johns", "Springerville", "Eagar"],
    "Cochise": ["Sierra Vista", "Bisbee", "Douglas", "Willcox", "Benson", "Tombstone"],
    "Coconino": ["Flagstaff", "Page", "Sedona", "Williams", "Fredonia", "Tusayan"],
    "Gila": ["Globe", "Miami", "Payson", "Star Valley"],
    "Graham": ["Safford", "Thatcher", "Pima"],
    "Greenlee": ["Clifton", "Duncan", "Morenci"],
    "La Paz": ["Parker", "Quartzsite"],
    "Maricopa": ["Phoenix", "Mesa", "Scottsdale", "Chandler", "Tempe", "Gilbert", "Glendale", "Peoria", "Surprise", "Avondale", "Goodyear", "Buckeye", "Litchfield Park", "Cave Creek", "Carefree", "Fountain Hills", "Paradise Valley", "Queen Creek", "Tolleson", "El Mirage", "Wickenburg", "Youngtown"],
    "Mohave": ["Kingman", "Lake Havasu City", "Bullhead City", "Colorado City", "Dolan Springs"],
    "Navajo": ["Show Low", "Snowflake", "Taylor", "Holbrook", "Winslow", "Pinetop-Lakeside"],
    "Pima": ["Tucson", "Marana", "Oro Valley", "Sahuarita", "South Tucson", "Catalina Foothills", "Casas Adobes", "Flowing Wells"],
    "Pinal": ["Casa Grande", "Florence", "Coolidge", "Eloy", "Apache Junction", "Maricopa", "Queen Creek", "San Tan Valley"],
    "Santa Cruz": ["Nogales", "Tubac", "Patagonia", "Rio Rico"],
    "Yavapai": ["Prescott", "Prescott Valley", "Cottonwood", "Camp Verde", "Clarkdale", "Chino Valley", "Dewey-Humboldt", "Jerome", "Sedona"],
    "Yuma": ["Yuma", "San Luis", "Somerton", "Wellton", "Fortuna Foothills"]
  },
  AR: {
    "Benton": ["Bentonville", "Rogers", "Bella Vista", "Siloam Springs", "Centerton", "Pea Ridge", "Gravette", "Lowell", "Decatur", "Gentry", "Cave Springs"],
    "Craighead": ["Jonesboro", "Brookland", "Bay", "Bono", "Lake City"],
    "Faulkner": ["Conway", "Greenbrier", "Vilonia", "Mayflower", "Guy", "Wooster"],
    "Garland": ["Hot Springs", "Hot Springs Village", "Lonsdale", "Mountain Pine", "Royal"],
    "Jefferson": ["Pine Bluff", "White Hall", "Redfield", "Sherrill", "Altheimer"],
    "Pulaski": ["Little Rock", "North Little Rock", "Jacksonville", "Sherwood", "Maumelle", "Wrightsville", "Sweet Home", "Cammack Village"],
    "Saline": ["Benton", "Bryant", "Bauxite", "Shannon Hills", "Salem", "Traskwood", "Haskell"],
    "Sebastian": ["Fort Smith", "Greenwood", "Barling", "Lavaca", "Hackett", "Hartford", "Bonanza"],
    "Washington": ["Fayetteville", "Springdale", "Farmington", "Elkins", "Goshen", "Greenland", "Johnson", "Lincoln", "Prairie Grove", "Tontitown", "West Fork"],
    "White": ["Searcy", "Beebe", "Bald Knob", "Bradford", "Judsonia", "Kensett", "McRae", "Pangburn", "Rose Bud"]
  },
  CA: {
    "Alameda": ["Oakland", "Berkeley", "Fremont", "Hayward", "San Leandro", "Livermore", "Pleasanton", "Alameda", "Union City", "Newark", "Dublin", "Emeryville", "Albany", "Piedmont"],
    "Butte": ["Chico", "Oroville", "Paradise", "Gridley", "Biggs"],
    "Contra Costa": ["Concord", "Richmond", "Antioch", "Walnut Creek", "San Ramon", "Pittsburg", "Brentwood", "Danville", "Oakley", "Pleasant Hill", "Martinez", "Pinole", "Hercules", "El Cerrito", "Lafayette", "Moraga", "Orinda", "Clayton"],
    "El Dorado": ["Placerville", "South Lake Tahoe", "Cameron Park", "El Dorado Hills", "Shingle Springs", "Pollock Pines"],
    "Fresno": ["Fresno", "Clovis", "Sanger", "Selma", "Reedley", "Kerman", "Kingsburg", "Parlier", "Coalinga", "Fowler", "Mendota", "Orange Cove", "Huron"],
    "Humboldt": ["Eureka", "Arcata", "Fortuna", "McKinleyville", "Blue Lake"],
    "Imperial": ["El Centro", "Calexico", "Brawley", "Imperial", "Holtville"],
    "Kern": ["Bakersfield", "Delano", "Ridgecrest", "Tehachapi", "Wasco", "Shafter", "Arvin", "California City", "McFarland", "Taft", "Maricopa"],
    "Kings": ["Hanford", "Lemoore", "Corcoran", "Avenal"],
    "Los Angeles": ["Los Angeles", "Long Beach", "Santa Clarita", "Glendale", "Lancaster", "Palmdale", "Pomona", "Torrance", "Pasadena", "El Monte", "Downey", "Inglewood", "West Covina", "Norwalk", "Burbank", "Compton", "South Gate", "Carson", "Santa Monica", "Whittier", "Hawthorne", "Alhambra", "Lakewood", "Bellflower", "Baldwin Park", "Lynwood", "Redondo Beach", "Pico Rivera", "Montebello", "Monterey Park", "Gardena", "Arcadia", "Diamond Bar", "Paramount", "Rosemead", "Glendora", "Covina", "Azusa", "West Hollywood", "Culver City", "La Mirada", "Rancho Palos Verdes", "Walnut", "Manhattan Beach", "Beverly Hills", "Claremont", "San Dimas", "Hermosa Beach", "La Verne", "Calabasas", "Agoura Hills", "Malibu"],
    "Marin": ["San Rafael", "Novato", "Mill Valley", "Larkspur", "Corte Madera", "Sausalito", "Tiburon", "Fairfax", "San Anselmo", "Ross"],
    "Merced": ["Merced", "Los Banos", "Atwater", "Livingston", "Gustine"],
    "Monterey": ["Salinas", "Seaside", "Monterey", "Marina", "Pacific Grove", "Soledad", "King City", "Gonzales", "Greenfield"],
    "Napa": ["Napa", "American Canyon", "St. Helena", "Calistoga", "Yountville"],
    "Nevada": ["Grass Valley", "Nevada City", "Truckee", "Penn Valley"],
    "Orange": ["Anaheim", "Santa Ana", "Irvine", "Huntington Beach", "Garden Grove", "Fullerton", "Orange", "Costa Mesa", "Mission Viejo", "Lake Forest", "Newport Beach", "Buena Park", "Laguna Niguel", "Tustin", "Yorba Linda", "San Clemente", "Laguna Beach", "Westminster", "Cypress", "La Habra", "Placentia", "Dana Point", "Aliso Viejo", "Laguna Hills", "San Juan Capistrano", "Rancho Santa Margarita", "Brea", "Stanton", "Seal Beach", "Los Alamitos", "Villa Park"],
    "Placer": ["Roseville", "Rocklin", "Lincoln", "Auburn", "Loomis", "Colfax", "Granite Bay"],
    "Riverside": ["Riverside", "Moreno Valley", "Corona", "Murrieta", "Temecula", "Menifee", "Hemet", "Lake Elsinore", "Indio", "Perris", "Palm Desert", "Palm Springs", "San Jacinto", "Beaumont", "Banning", "Cathedral City", "La Quinta", "Coachella", "Rancho Mirage", "Norco", "Eastvale", "Wildomar", "Jurupa Valley", "Calimesa", "Desert Hot Springs", "Indian Wells"],
    "Sacramento": ["Sacramento", "Elk Grove", "Rancho Cordova", "Citrus Heights", "Folsom", "Galt", "Isleton", "North Highlands", "Arden-Arcade", "Carmichael", "Fair Oaks", "Orangevale"],
    "San Bernardino": ["San Bernardino", "Fontana", "Rancho Cucamonga", "Ontario", "Victorville", "Rialto", "Upland", "Chino", "Chino Hills", "Apple Valley", "Hesperia", "Redlands", "Highland", "Colton", "Yucaipa", "Montclair", "Loma Linda", "Barstow", "Twentynine Palms", "Yucca Valley", "Big Bear Lake", "Grand Terrace"],
    "San Diego": ["San Diego", "Chula Vista", "Oceanside", "Escondido", "Carlsbad", "El Cajon", "Vista", "San Marcos", "Encinitas", "National City", "La Mesa", "Santee", "Poway", "Imperial Beach", "Solana Beach", "Del Mar", "Lemon Grove", "Coronado", "Ramona", "Fallbrook", "Valley Center"],
    "San Francisco": ["San Francisco"],
    "San Joaquin": ["Stockton", "Tracy", "Manteca", "Lodi", "Lathrop", "Ripon", "Escalon"],
    "San Luis Obispo": ["San Luis Obispo", "Paso Robles", "Atascadero", "Arroyo Grande", "Morro Bay", "Pismo Beach", "Grover Beach"],
    "San Mateo": ["Daly City", "San Mateo", "Redwood City", "South San Francisco", "San Bruno", "Pacifica", "Foster City", "Belmont", "San Carlos", "Menlo Park", "Burlingame", "Millbrae", "Half Moon Bay", "East Palo Alto", "Hillsborough", "Atherton", "Woodside", "Portola Valley"],
    "Santa Barbara": ["Santa Barbara", "Santa Maria", "Lompoc", "Goleta", "Carpinteria", "Solvang", "Buellton", "Guadalupe"],
    "Santa Clara": ["San Jose", "Sunnyvale", "Santa Clara", "Mountain View", "Milpitas", "Cupertino", "Palo Alto", "Campbell", "Los Gatos", "Morgan Hill", "Gilroy", "Saratoga", "Los Altos", "Monte Sereno"],
    "Santa Cruz": ["Santa Cruz", "Watsonville", "Scotts Valley", "Capitola"],
    "Shasta": ["Redding", "Anderson", "Shasta Lake"],
    "Solano": ["Vallejo", "Fairfield", "Vacaville", "Suisun City", "Benicia", "Dixon", "Rio Vista"],
    "Sonoma": ["Santa Rosa", "Petaluma", "Rohnert Park", "Windsor", "Healdsburg", "Sonoma", "Cloverdale", "Cotati", "Sebastopol"],
    "Stanislaus": ["Modesto", "Turlock", "Ceres", "Riverbank", "Oakdale", "Patterson", "Newman", "Hughson", "Waterford"],
    "Tulare": ["Visalia", "Tulare", "Porterville", "Dinuba", "Lindsay", "Exeter", "Farmersville", "Woodlake"],
    "Ventura": ["Oxnard", "Thousand Oaks", "Simi Valley", "Ventura", "Camarillo", "Moorpark", "Santa Paula", "Fillmore", "Ojai", "Port Hueneme"],
    "Yolo": ["Davis", "Woodland", "West Sacramento", "Winters", "Esparto"]
  },
  CO: {
    "Adams": ["Aurora", "Thornton", "Northglenn", "Westminster", "Brighton", "Commerce City", "Federal Heights", "Bennett"],
    "Arapahoe": ["Aurora", "Centennial", "Littleton", "Englewood", "Greenwood Village", "Cherry Hills Village", "Sheridan", "Glendale", "Foxfield", "Deer Trail"],
    "Boulder": ["Boulder", "Longmont", "Louisville", "Lafayette", "Superior", "Erie", "Nederland", "Lyons", "Ward", "Jamestown"],
    "Broomfield": ["Broomfield"],
    "Denver": ["Denver"],
    "Douglas": ["Castle Rock", "Parker", "Lone Tree", "Highlands Ranch", "Castle Pines", "Larkspur", "Franktown", "Sedalia"],
    "Eagle": ["Vail", "Eagle", "Avon", "Edwards", "Gypsum", "Minturn", "Red Cliff"],
    "El Paso": ["Colorado Springs", "Fountain", "Security-Widefield", "Manitou Springs", "Monument", "Palmer Lake", "Woodland Park", "Calhan", "Falcon", "Cimarron Hills", "Ellicott", "Peyton"],
    "Garfield": ["Glenwood Springs", "Rifle", "Silt", "New Castle", "Parachute", "Carbondale"],
    "Jefferson": ["Lakewood", "Arvada", "Wheat Ridge", "Golden", "Edgewater", "Morrison", "Evergreen", "Conifer", "Indian Hills"],
    "La Plata": ["Durango", "Bayfield", "Ignacio"],
    "Larimer": ["Fort Collins", "Loveland", "Estes Park", "Berthoud", "Johnstown", "Timnath", "Wellington", "Windsor"],
    "Mesa": ["Grand Junction", "Fruita", "Palisade", "Clifton", "Collbran", "De Beque"],
    "Pitkin": ["Aspen", "Snowmass Village", "Basalt"],
    "Pueblo": ["Pueblo", "Pueblo West", "Boone", "Rye"],
    "Routt": ["Steamboat Springs", "Hayden", "Oak Creek", "Yampa"],
    "Summit": ["Breckenridge", "Frisco", "Dillon", "Silverthorne", "Keystone"],
    "Weld": ["Greeley", "Evans", "Windsor", "Firestone", "Frederick", "Dacono", "Fort Lupton", "Erie", "Johnstown", "Milliken", "Platteville", "Severance", "Mead"]
  },
  CT: {
    "Fairfield": ["Bridgeport", "Stamford", "Norwalk", "Danbury", "Fairfield", "Stratford", "Shelton", "Trumbull", "Greenwich", "Westport", "Darien", "New Canaan", "Ridgefield", "Weston", "Wilton", "Redding", "Easton", "Monroe", "Newtown", "Bethel", "Brookfield", "New Fairfield", "Sherman"],
    "Hartford": ["Hartford", "New Britain", "West Hartford", "Bristol", "Manchester", "East Hartford", "Enfield", "Glastonbury", "Simsbury", "Farmington", "Avon", "South Windsor", "Wethersfield", "Windsor", "Rocky Hill", "Newington", "Bloomfield", "Canton", "Granby", "Southington", "Berlin", "Burlington", "Plainville"],
    "Litchfield": ["Torrington", "New Milford", "Litchfield", "Thomaston", "Winchester", "Salisbury", "Sharon", "Kent", "Cornwall", "Goshen"],
    "Middlesex": ["Middletown", "Cromwell", "Durham", "East Hampton", "Portland", "Haddam", "Chester", "Clinton", "Deep River", "Essex", "Killingworth", "Old Saybrook", "Westbrook"],
    "New Haven": ["New Haven", "Waterbury", "Meriden", "Milford", "West Haven", "Hamden", "Cheshire", "Branford", "East Haven", "Guilford", "Wallingford", "Naugatuck", "North Haven", "Woodbridge", "Orange", "Bethany", "Seymour", "Ansonia", "Derby", "Beacon Falls", "Prospect", "Southbury", "Madison", "North Branford"],
    "New London": ["New London", "Norwich", "Groton", "Waterford", "East Lyme", "Montville", "Ledyard", "Stonington", "Colchester", "Old Lyme"],
    "Tolland": ["Vernon", "Mansfield", "Tolland", "Coventry", "Ellington", "Stafford", "Somers", "Bolton", "Andover", "Columbia", "Hebron", "Willington", "Union"],
    "Windham": ["Windham", "Willimantic", "Putnam", "Plainfield", "Killingly", "Brooklyn", "Sterling", "Thompson", "Woodstock", "Canterbury", "Hampton"]
  },
  DE: {
    "Kent": ["Dover", "Milford", "Smyrna", "Harrington", "Camden", "Clayton", "Felton", "Frederica", "Houston", "Wyoming"],
    "New Castle": ["Wilmington", "Newark", "Middletown", "Bear", "Hockessin", "Claymont", "Pike Creek", "New Castle", "Brookside", "Elsmere", "Delaware City", "Odessa", "Townsend"],
    "Sussex": ["Georgetown", "Lewes", "Rehoboth Beach", "Seaford", "Milford", "Millsboro", "Bethany Beach", "Dewey Beach", "Fenwick Island", "Laurel", "Bridgeville", "Delmar", "Milton"]
  },
  FL: {
    "Alachua": ["Gainesville", "Alachua", "Newberry", "High Springs", "Hawthorne", "Waldo", "Archer", "Micanopy"],
    "Bay": ["Panama City", "Panama City Beach", "Lynn Haven", "Callaway", "Springfield", "Mexico Beach"],
    "Brevard": ["Melbourne", "Palm Bay", "Titusville", "Cocoa", "Rockledge", "Merritt Island", "Cocoa Beach", "Satellite Beach", "Indian Harbour Beach", "Indialantic", "West Melbourne", "Cape Canaveral", "Grant-Valkaria", "Malabar"],
    "Broward": ["Fort Lauderdale", "Hollywood", "Pembroke Pines", "Miramar", "Coral Springs", "Davie", "Plantation", "Sunrise", "Pompano Beach", "Deerfield Beach", "Coconut Creek", "Tamarac", "Margate", "Lauderhill", "Weston", "Cooper City", "Oakland Park", "Hallandale Beach", "Lauderdale Lakes", "Wilton Manors", "Parkland", "Southwest Ranches", "Lighthouse Point", "Sea Ranch Lakes"],
    "Charlotte": ["Punta Gorda", "Port Charlotte", "Englewood", "Murdock", "Rotonda West"],
    "Citrus": ["Crystal River", "Inverness", "Homosassa", "Lecanto", "Beverly Hills"],
    "Clay": ["Green Cove Springs", "Orange Park", "Middleburg", "Fleming Island", "Keystone Heights", "Oakleaf"],
    "Collier": ["Naples", "Marco Island", "Immokalee", "Golden Gate", "Ave Maria"],
    "Duval": ["Jacksonville", "Jacksonville Beach", "Atlantic Beach", "Neptune Beach", "Baldwin"],
    "Escambia": ["Pensacola", "Perdido Key", "Brent", "Myrtle Grove", "Bellview", "Ensley", "Ferry Pass", "Gonzalez", "Warrington", "Century"],
    "Flagler": ["Palm Coast", "Flagler Beach", "Bunnell", "Marineland"],
    "Hernando": ["Brooksville", "Spring Hill", "Weeki Wachee"],
    "Hillsborough": ["Tampa", "Brandon", "Riverview", "Plant City", "Valrico", "Temple Terrace", "Lutz", "Ruskin", "Apollo Beach", "Fish Hawk", "Lithia", "Seffner", "Thonotosassa", "Wimauma"],
    "Indian River": ["Vero Beach", "Sebastian", "Fellsmere", "Indian River Shores", "Orchid"],
    "Lake": ["Leesburg", "Clermont", "Eustis", "Tavares", "Mount Dora", "Lady Lake", "Groveland", "Minneola", "Fruitland Park", "Mascotte", "Umatilla", "Montverde"],
    "Lee": ["Fort Myers", "Cape Coral", "Bonita Springs", "Estero", "Lehigh Acres", "North Fort Myers", "Sanibel", "Fort Myers Beach"],
    "Leon": ["Tallahassee"],
    "Manatee": ["Bradenton", "Palmetto", "Lakewood Ranch", "Anna Maria", "Holmes Beach", "Longboat Key", "Parrish", "Ellenton", "Myakka City"],
    "Marion": ["Ocala", "Belleview", "Dunnellon", "The Villages", "Silver Springs Shores"],
    "Martin": ["Stuart", "Jensen Beach", "Palm City", "Indiantown", "Hobe Sound"],
    "Miami-Dade": ["Miami", "Hialeah", "Miami Gardens", "Miami Beach", "Homestead", "North Miami", "Doral", "Coral Gables", "Kendall", "Miami Lakes", "Aventura", "North Miami Beach", "Cutler Bay", "Palmetto Bay", "Pinecrest", "Sunny Isles Beach", "Key Biscayne", "Sweetwater", "Opa-locka", "Florida City", "South Miami", "Bal Harbour", "Surfside", "Bay Harbor Islands"],
    "Monroe": ["Key West", "Key Largo", "Marathon", "Islamorada", "Tavernier", "Big Pine Key", "Stock Island"],
    "Nassau": ["Fernandina Beach", "Yulee", "Callahan", "Hilliard"],
    "Okaloosa": ["Fort Walton Beach", "Crestview", "Destin", "Niceville", "Valparaiso", "Mary Esther", "Shalimar", "Cinco Bayou"],
    "Orange": ["Orlando", "Winter Garden", "Apopka", "Ocoee", "Winter Park", "Maitland", "Belle Isle", "Windermere", "Oakland", "Eatonville", "Dr. Phillips", "Hunters Creek"],
    "Osceola": ["Kissimmee", "St. Cloud", "Poinciana", "Celebration"],
    "Palm Beach": ["West Palm Beach", "Boca Raton", "Boynton Beach", "Delray Beach", "Jupiter", "Lake Worth Beach", "Palm Beach Gardens", "Royal Palm Beach", "Wellington", "Greenacres", "Riviera Beach", "Lantana", "North Palm Beach", "Palm Beach", "Loxahatchee", "Palm Springs", "Tequesta", "Belle Glade", "Pahokee"],
    "Pasco": ["New Port Richey", "Dade City", "Zephyrhills", "Land O' Lakes", "Wesley Chapel", "Trinity", "Hudson", "Port Richey", "Holiday", "Lutz", "San Antonio", "Shady Hills"],
    "Pinellas": ["St. Petersburg", "Clearwater", "Largo", "Palm Harbor", "Dunedin", "Tarpon Springs", "Pinellas Park", "Seminole", "Safety Harbor", "Oldsmar", "Gulfport", "Indian Rocks Beach", "Madeira Beach", "Treasure Island", "St. Pete Beach", "Belleair", "Kenneth City"],
    "Polk": ["Lakeland", "Winter Haven", "Bartow", "Auburndale", "Haines City", "Lake Wales", "Eagle Lake", "Frostproof", "Fort Meade", "Mulberry", "Davenport"],
    "Santa Rosa": ["Milton", "Gulf Breeze", "Pace", "Navarre", "Jay"],
    "Sarasota": ["Sarasota", "North Port", "Venice", "Osprey", "Nokomis", "Longboat Key", "Englewood", "Siesta Key"],
    "Seminole": ["Sanford", "Lake Mary", "Altamonte Springs", "Casselberry", "Winter Springs", "Longwood", "Oviedo", "Geneva"],
    "St. Johns": ["St. Augustine", "Ponte Vedra Beach", "St. Augustine Beach", "Nocatee", "Hastings", "Fruit Cove", "World Golf Village"],
    "St. Lucie": ["Port St. Lucie", "Fort Pierce", "St. Lucie West", "Tradition"],
    "Volusia": ["Daytona Beach", "Deltona", "Ormond Beach", "Port Orange", "New Smyrna Beach", "DeLand", "Edgewater", "Holly Hill", "Orange City", "DeBary", "Pierson", "Lake Helen", "Ponce Inlet", "Daytona Beach Shores"]
  },
  GA: {
    "Bibb": ["Macon"],
    "Chatham": ["Savannah", "Pooler", "Garden City", "Thunderbolt", "Tybee Island", "Bloomingdale"],
    "Cherokee": ["Canton", "Woodstock", "Holly Springs", "Ball Ground", "Waleska"],
    "Clarke": ["Athens", "Winterville", "Bogart"],
    "Clayton": ["Jonesboro", "Morrow", "Riverdale", "Forest Park", "Lake City", "Lovejoy"],
    "Cobb": ["Marietta", "Smyrna", "Kennesaw", "Acworth", "Powder Springs", "Austell", "Mableton", "Vinings"],
    "Columbia": ["Evans", "Martinez", "Grovetown", "Harlem", "Appling"],
    "Coweta": ["Newnan", "Senoia", "Grantville", "Sharpsburg", "Turin"],
    "DeKalb": ["Decatur", "Stone Mountain", "Dunwoody", "Brookhaven", "Tucker", "Clarkston", "Doraville", "Lithonia", "Avondale Estates", "Chamblee"],
    "Dougherty": ["Albany"],
    "Douglas": ["Douglasville", "Lithia Springs", "Villa Rica"],
    "Fayette": ["Peachtree City", "Fayetteville", "Tyrone", "Brooks", "Woolsey"],
    "Floyd": ["Rome", "Cave Spring", "Shannon"],
    "Forsyth": ["Cumming", "Coal Mountain"],
    "Fulton": ["Atlanta", "Roswell", "Johns Creek", "Alpharetta", "Sandy Springs", "Milton", "College Park", "East Point", "Union City", "Hapeville", "Fairburn", "Palmetto", "Chattahoochee Hills", "South Fulton", "Mountain Park"],
    "Glynn": ["Brunswick", "St. Simons Island", "Jekyll Island", "Sea Island"],
    "Gwinnett": ["Lawrenceville", "Duluth", "Suwanee", "Snellville", "Lilburn", "Norcross", "Buford", "Dacula", "Grayson", "Loganville", "Peachtree Corners", "Sugar Hill", "Berkeley Lake", "Rest Haven"],
    "Hall": ["Gainesville", "Flowery Branch", "Oakwood", "Lula", "Clermont"],
    "Henry": ["McDonough", "Stockbridge", "Hampton", "Locust Grove"],
    "Houston": ["Warner Robins", "Perry", "Centerville", "Byron"],
    "Lowndes": ["Valdosta", "Hahira", "Lake Park", "Dasher", "Remerton"],
    "Muscogee": ["Columbus"],
    "Paulding": ["Dallas", "Hiram"],
    "Richmond": ["Augusta"],
    "Whitfield": ["Dalton", "Varnell", "Tunnel Hill", "Cohutta"]
  },
  HI: {
    "Hawaii": ["Hilo", "Kailua-Kona", "Captain Cook", "Waikoloa Village", "Waimea", "Pahoa", "Keaau", "Hawaiian Paradise Park"],
    "Honolulu": ["Honolulu", "Pearl City", "Kailua", "Kaneohe", "Mililani Town", "Ewa Beach", "Kapolei", "Aiea", "Waipahu", "Hawaii Kai", "Waikiki"],
    "Kauai": ["Lihue", "Kapaa", "Koloa", "Poipu", "Hanalei", "Princeville", "Waimea", "Hanapepe", "Kalaheo", "Eleele"],
    "Maui": ["Kahului", "Wailuku", "Kihei", "Lahaina", "Pukalani", "Makawao", "Paia", "Haiku", "Hana", "Kula"]
  },
  ID: {
    "Ada": ["Boise", "Meridian", "Eagle", "Garden City", "Kuna", "Star", "Hidden Springs"],
    "Bannock": ["Pocatello", "Chubbuck", "Inkom", "Lava Hot Springs", "McCammon", "Downey"],
    "Bingham": ["Blackfoot", "Shelley", "Firth", "Aberdeen"],
    "Blaine": ["Hailey", "Ketchum", "Sun Valley", "Bellevue", "Carey"],
    "Bonneville": ["Idaho Falls", "Ammon", "Iona", "Ucon", "Swan Valley"],
    "Canyon": ["Nampa", "Caldwell", "Middleton", "Notus", "Greenleaf", "Melba", "Parma", "Wilder"],
    "Kootenai": ["Coeur d'Alene", "Post Falls", "Hayden", "Rathdrum", "Spirit Lake", "Dalton Gardens", "Athol", "Harrison"],
    "Latah": ["Moscow", "Troy", "Genesee", "Deary", "Bovill", "Potlatch", "Juliaetta"],
    "Madison": ["Rexburg", "Sugar City"],
    "Nez Perce": ["Lewiston"],
    "Twin Falls": ["Twin Falls", "Kimberly", "Filer", "Buhl", "Hansen", "Hollister", "Castleford"]
  },
  IL: {
    "Champaign": ["Champaign", "Urbana", "Rantoul", "Mahomet", "Savoy", "St. Joseph", "Tolono", "Fisher"],
    "Cook": ["Chicago", "Evanston", "Skokie", "Oak Park", "Cicero", "Arlington Heights", "Schaumburg", "Palatine", "Des Plaines", "Berwyn", "Mount Prospect", "Tinley Park", "Oak Lawn", "Orland Park", "Niles", "Park Ridge", "Hoffman Estates", "Elk Grove Village", "Wheeling", "Buffalo Grove", "Streamwood", "Glenview", "Northbrook", "Wilmette", "Winnetka", "Kenilworth", "Glencoe", "Highland Park", "Lake Forest", "Barrington", "Hanover Park", "Rolling Meadows", "Calumet City", "Harvey", "Dolton", "Lansing", "South Holland", "Matteson", "Homewood", "Flossmoor", "Olympia Fields", "Country Club Hills", "Richton Park", "Alsip", "Blue Island", "Evergreen Park", "Oak Forest", "Chicago Heights"],
    "DeKalb": ["DeKalb", "Sycamore", "Genoa", "Sandwich", "Somonauk"],
    "DuPage": ["Naperville", "Wheaton", "Downers Grove", "Elmhurst", "Lombard", "Carol Stream", "Glen Ellyn", "Addison", "Villa Park", "Woodridge", "Lisle", "Westmont", "Bensenville", "Roselle", "Bloomingdale", "Hinsdale", "Clarendon Hills", "Darien", "Willowbrook", "Warrenville", "West Chicago", "Winfield", "Oak Brook", "Oakbrook Terrace"],
    "Kane": ["Aurora", "Elgin", "St. Charles", "Batavia", "Geneva", "South Elgin", "Carpentersville", "East Dundee", "West Dundee", "Gilberts", "Hampshire", "North Aurora", "Sugar Grove", "Montgomery"],
    "Kankakee": ["Kankakee", "Bourbonnais", "Bradley", "Manteno"],
    "Lake": ["Waukegan", "North Chicago", "Mundelein", "Vernon Hills", "Libertyville", "Gurnee", "Grayslake", "Round Lake", "Highland Park", "Lake Forest", "Lake Zurich", "Deerfield", "Lincolnshire", "Lake Bluff", "Lake Villa", "Antioch", "Wauconda", "Fox Lake", "Bannockburn", "Barrington"],
    "LaSalle": ["Ottawa", "Peru", "LaSalle", "Streator", "Oglesby", "Marseilles", "Mendota", "Utica"],
    "Macon": ["Decatur", "Forsyth", "Mt. Zion", "Maroa"],
    "Madison": ["Edwardsville", "Glen Carbon", "Collinsville", "Granite City", "Alton", "Maryville", "Troy", "Godfrey", "Wood River", "Bethalto", "Highland", "Pontoon Beach"],
    "McLean": ["Bloomington", "Normal", "Lexington", "Heyworth", "Le Roy"],
    "Peoria": ["Peoria", "Peoria Heights", "West Peoria", "Bartonville", "Chillicothe", "Dunlap", "Princeville"],
    "Rock Island": ["Rock Island", "Moline", "East Moline", "Silvis", "Milan", "Hampton"],
    "Sangamon": ["Springfield", "Chatham", "Rochester", "Sherman", "Riverton", "Jerome", "Williamsville", "Leland Grove"],
    "St. Clair": ["Belleville", "O'Fallon", "Swansea", "Fairview Heights", "Shiloh", "Scott AFB", "East St. Louis", "Cahokia Heights", "Mascoutah", "Lebanon", "Millstadt"],
    "Tazewell": ["Pekin", "Morton", "Washington", "East Peoria", "North Pekin", "Creve Coeur", "Tremont", "Delavan", "Mackinaw"],
    "Will": ["Joliet", "Bolingbrook", "Romeoville", "Plainfield", "Lockport", "New Lenox", "Mokena", "Frankfort", "Homer Glen", "Shorewood", "Crest Hill", "Channahon", "Minooka", "Manhattan", "Monee"],
    "Winnebago": ["Rockford", "Loves Park", "Machesney Park", "Roscoe", "Cherry Valley", "Winnebago", "South Beloit", "Pecatonica"]
  },
  IN: {
    "Allen": ["Fort Wayne", "New Haven", "Grabill", "Huntertown", "Leo-Cedarville", "Monroeville", "Woodburn"],
    "Delaware": ["Muncie", "Yorktown", "Albany", "Daleville", "Eaton", "Gaston"],
    "Elkhart": ["Elkhart", "Goshen", "Nappanee", "Middlebury", "Bristol", "Wakarusa"],
    "Hamilton": ["Carmel", "Fishers", "Noblesville", "Westfield", "Cicero", "Arcadia", "Sheridan", "Atlanta"],
    "Hendricks": ["Plainfield", "Brownsburg", "Avon", "Danville", "Lizton", "Pittsboro"],
    "Johnson": ["Greenwood", "Franklin", "Edinburgh", "Whiteland", "Bargersville", "New Whiteland", "Trafalgar", "Prince's Lakes"],
    "Lake": ["Gary", "Hammond", "East Chicago", "Munster", "Schererville", "Crown Point", "Griffith", "Dyer", "Highland", "Merrillville", "Hobart", "St. John", "Cedar Lake", "Lowell", "Whiting", "Lake Station"],
    "LaPorte": ["Michigan City", "La Porte", "Westville", "Rolling Prairie", "Wanatah"],
    "Madison": ["Anderson", "Pendleton", "Elwood", "Frankton", "Edgewood", "Chesterfield", "Alexandria", "Lapel"],
    "Marion": ["Indianapolis", "Lawrence", "Beech Grove", "Speedway", "Southport", "Cumberland", "Clermont"],
    "Monroe": ["Bloomington", "Ellettsville"],
    "Porter": ["Portage", "Valparaiso", "Chesterton", "Burns Harbor"],
    "St. Joseph": ["South Bend", "Mishawaka", "Granger", "Osceola", "Walkerton"],
    "Tippecanoe": ["Lafayette", "West Lafayette", "Battle Ground", "Dayton"],
    "Vanderburgh": ["Evansville", "Newburgh", "Darmstadt"],
    "Vigo": ["Terre Haute", "West Terre Haute", "Riley", "Seelyville"]
  },
  IA: {
    "Black Hawk": ["Waterloo", "Cedar Falls", "Evansdale", "Elk Run Heights", "Hudson", "La Porte City"],
    "Dallas": ["Waukee", "Clive", "West Des Moines", "Grimes", "Perry", "Dallas Center", "Adel", "De Soto", "Woodward"],
    "Dubuque": ["Dubuque", "Asbury", "Cascade", "Dyersville", "Epworth", "Farley", "Peosta"],
    "Johnson": ["Iowa City", "Coralville", "North Liberty", "Tiffin", "Solon", "Lone Tree", "Oxford", "Hills"],
    "Linn": ["Cedar Rapids", "Marion", "Hiawatha", "Robins", "Ely", "Fairfax", "Lisbon", "Mount Vernon"],
    "Polk": ["Des Moines", "West Des Moines", "Ankeny", "Urbandale", "Johnston", "Altoona", "Pleasant Hill", "Bondurant", "Clive", "Grimes", "Mitchellville"],
    "Pottawattamie": ["Council Bluffs", "Carter Lake", "Oakland", "Avoca", "Treynor", "Underwood"],
    "Scott": ["Davenport", "Bettendorf", "Eldridge", "Le Claire", "Princeton", "Walcott", "Blue Grass", "Buffalo", "Long Grove"],
    "Story": ["Ames", "Nevada", "Huxley", "Story City", "Gilbert", "Cambridge", "Colo", "Maxwell"],
    "Woodbury": ["Sioux City", "Sergeant Bluff", "Moville", "Correctionville", "Sloan"]
  },
  KS: {
    "Douglas": ["Lawrence", "Eudora", "Baldwin City", "Lecompton"],
    "Johnson": ["Overland Park", "Olathe", "Lenexa", "Shawnee", "Leawood", "Prairie Village", "Merriam", "Mission", "Roeland Park", "Fairway", "Gardner", "Spring Hill", "De Soto", "Edgerton", "Westwood", "Mission Hills"],
    "Reno": ["Hutchinson", "South Hutchinson", "Nickerson", "Haven", "Buhler"],
    "Riley": ["Manhattan", "Ogden", "Riley", "Fort Riley"],
    "Saline": ["Salina", "Assaria", "Brookville", "Gypsum"],
    "Sedgwick": ["Wichita", "Derby", "Andover", "Maize", "Haysville", "Park City", "Bel Aire", "Goddard", "Valley Center", "Kechi", "Mulvane", "Clearwater", "Colwich", "Bentley", "Cheney"],
    "Shawnee": ["Topeka", "Silver Lake", "Rossville", "Willard", "Auburn"],
    "Wyandotte": ["Kansas City", "Bonner Springs", "Edwardsville"]
  },
  KY: {
    "Boone": ["Florence", "Union", "Burlington", "Hebron", "Walton"],
    "Daviess": ["Owensboro", "Whitesville"],
    "Fayette": ["Lexington"],
    "Franklin": ["Frankfort"],
    "Hardin": ["Elizabethtown", "Radcliff", "Vine Grove", "West Point", "Fort Knox"],
    "Jefferson": ["Louisville", "St. Matthews", "Jeffersontown", "Shively", "Lyndon", "Middletown", "Prospect", "Anchorage", "Indian Hills", "Hurstbourne"],
    "Kenton": ["Covington", "Erlanger", "Independence", "Edgewood", "Fort Wright", "Villa Hills", "Elsmere", "Taylor Mill", "Crestview Hills", "Lakeside Park"],
    "Madison": ["Richmond", "Berea"],
    "McCracken": ["Paducah"],
    "Pike": ["Pikeville", "Elkhorn City", "Coal Run Village"],
    "Warren": ["Bowling Green", "Smiths Grove"]
  },
  LA: {
    "Caddo": ["Shreveport", "Blanchard", "Greenwood", "Oil City", "Vivian"],
    "Calcasieu": ["Lake Charles", "Sulphur", "Westlake", "DeQuincy", "Iowa", "Moss Bluff"],
    "East Baton Rouge": ["Baton Rouge", "Baker", "Zachary", "Central", "Greenwell Springs", "Merrydale"],
    "Jefferson": ["Metairie", "Kenner", "Harvey", "Marrero", "Gretna", "Terrytown", "Westwego", "Bridge City", "Waggaman", "Grand Isle"],
    "Lafayette": ["Lafayette", "Broussard", "Scott", "Youngsville", "Carencro", "Duson", "Milton"],
    "Lafourche": ["Thibodaux", "Raceland", "Lockport", "Larose", "Cut Off", "Chackbay", "Mathews"],
    "Livingston": ["Denham Springs", "Walker", "Livingston", "Albany", "Watson", "French Settlement"],
    "Orleans": ["New Orleans"],
    "Ouachita": ["Monroe", "West Monroe"],
    "Rapides": ["Alexandria", "Pineville", "Ball", "Boyce", "Woodworth"],
    "St. Tammany": ["Slidell", "Mandeville", "Covington", "Madisonville", "Abita Springs", "Pearl River", "Lacombe"],
    "Tangipahoa": ["Hammond", "Ponchatoula", "Amite City", "Independence", "Kentwood", "Robert"]
  },
  ME: {
    "Androscoggin": ["Lewiston", "Auburn", "Lisbon", "Sabattus", "Turner", "Poland", "Mechanic Falls", "Livermore Falls", "Leeds", "Durham", "Greene", "Minot"],
    "Cumberland": ["Portland", "South Portland", "Westbrook", "Scarborough", "Gorham", "Windham", "Falmouth", "Cape Elizabeth", "Yarmouth", "Freeport", "Brunswick", "Cumberland", "Gray", "Bridgton", "Standish", "Raymond"],
    "Kennebec": ["Augusta", "Waterville", "Winslow", "Gardiner", "Hallowell", "Oakland", "Fairfield", "Monmouth", "Belgrade"],
    "Penobscot": ["Bangor", "Brewer", "Old Town", "Orono", "Hampden", "Hermon", "Milford", "Veazie"],
    "York": ["Biddeford", "Saco", "Sanford", "Kennebunk", "Kennebunkport", "Wells", "Old Orchard Beach", "Kittery", "Berwick", "South Berwick", "Alfred", "Buxton", "Hollis", "Limerick", "Waterboro", "York"]
  },
  MD: {
    "Anne Arundel": ["Annapolis", "Glen Burnie", "Severna Park", "Crofton", "Odenton", "Pasadena", "Linthicum", "Arnold", "Parole", "Gambrills", "Millersville", "Edgewater", "Severn", "Laurel"],
    "Baltimore": ["Towson", "Pikesville", "Owings Mills", "Cockeysville", "Dundalk", "Perry Hall", "White Marsh", "Reisterstown", "Sparks", "Catonsville", "Randallstown", "Lutherville-Timonium", "Hunt Valley", "Essex", "Middle River", "Parkville"],
    "Baltimore City": ["Baltimore"],
    "Carroll": ["Westminster", "Eldersburg", "Hampstead", "Sykesville", "Taneytown", "Manchester", "Mount Airy"],
    "Charles": ["Waldorf", "La Plata", "Indian Head", "White Plains", "Bryans Road"],
    "Frederick": ["Frederick", "Thurmont", "Middletown", "Walkersville", "Brunswick", "Emmitsburg", "New Market", "Myersville", "Urbana"],
    "Harford": ["Bel Air", "Aberdeen", "Havre de Grace", "Edgewood", "Joppa", "Fallston", "Forest Hill", "Churchville", "Jarrettsville"],
    "Howard": ["Columbia", "Ellicott City", "Elkridge", "Fulton", "Highland", "Clarksville", "Laurel", "Jessup", "Savage", "North Laurel"],
    "Montgomery": ["Rockville", "Bethesda", "Silver Spring", "Gaithersburg", "Germantown", "Potomac", "Olney", "Takoma Park", "Wheaton", "Kensington", "Chevy Chase", "Clarksburg", "Poolesville", "Burtonsville", "Aspen Hill", "North Bethesda", "Damascus", "Colesville", "White Oak"],
    "Prince George's": ["College Park", "Bowie", "Laurel", "Hyattsville", "Greenbelt", "Upper Marlboro", "Oxon Hill", "Largo", "Fort Washington", "Clinton", "Temple Hills", "Suitland", "Landover", "District Heights", "Bladensburg", "Riverdale Park", "New Carrollton", "Cheverly"],
    "Washington": ["Hagerstown", "Boonsboro", "Hancock", "Williamsport", "Smithsburg", "Clear Spring", "Funkstown", "Sharpsburg", "Keedysville"]
  },
  MA: {
    "Barnstable": ["Barnstable", "Falmouth", "Sandwich", "Yarmouth", "Mashpee", "Bourne", "Harwich", "Dennis", "Brewster", "Chatham", "Eastham", "Orleans", "Wellfleet", "Truro", "Provincetown"],
    "Berkshire": ["Pittsfield", "North Adams", "Great Barrington", "Williamstown", "Lee", "Lenox", "Dalton", "Adams", "Stockbridge", "Sheffield"],
    "Bristol": ["New Bedford", "Fall River", "Taunton", "Attleboro", "Dartmouth", "Easton", "North Attleborough", "Somerset", "Mansfield", "Seekonk", "Rehoboth", "Swansea", "Dighton", "Raynham", "Berkley", "Freetown", "Acushnet", "Westport", "Fairhaven"],
    "Essex": ["Salem", "Lawrence", "Haverhill", "Peabody", "Methuen", "Beverly", "Gloucester", "Lynn", "Andover", "North Andover", "Danvers", "Marblehead", "Amesbury", "Newburyport", "Ipswich", "Swampscott", "Hamilton", "Wenham", "Topsfield", "Middleton", "Manchester-by-the-Sea", "Rockport", "Essex", "Georgetown", "Groveland", "Merrimac", "West Newbury", "Rowley", "Salisbury", "Nahant"],
    "Franklin": ["Greenfield", "Montague", "Deerfield", "Shelburne", "Orange", "Sunderland", "Northfield"],
    "Hampden": ["Springfield", "Chicopee", "Holyoke", "Westfield", "West Springfield", "Agawam", "Ludlow", "East Longmeadow", "Longmeadow", "Wilbraham", "Palmer", "Hampden", "Monson", "Russell", "Southwick"],
    "Hampshire": ["Amherst", "Northampton", "Easthampton", "South Hadley", "Hadley", "Ware", "Belchertown", "Williamsburg", "Hatfield", "Granby"],
    "Middlesex": ["Cambridge", "Lowell", "Somerville", "Newton", "Framingham", "Waltham", "Malden", "Medford", "Arlington", "Lexington", "Burlington", "Woburn", "Billerica", "Chelmsford", "Marlborough", "Natick", "Watertown", "Acton", "Concord", "Bedford", "Reading", "Wakefield", "Stoneham", "Melrose", "Winchester", "Tewksbury", "Dracut", "Westford", "Sudbury", "Wayland", "Lincoln", "Hopkinton", "Holliston", "Hudson", "Maynard", "Ashland", "Littleton", "Groton", "Pepperell", "Ayer", "Shirley", "Townsend", "Dunstable"],
    "Norfolk": ["Quincy", "Brookline", "Weymouth", "Braintree", "Milton", "Needham", "Dedham", "Norwood", "Wellesley", "Franklin", "Stoughton", "Canton", "Randolph", "Holbrook", "Medfield", "Millis", "Walpole", "Sharon", "Foxborough", "Wrentham", "Norfolk", "Plainville", "Medway", "Bellingham", "Dover", "Cohasset"],
    "Plymouth": ["Plymouth", "Brockton", "Middleborough", "Bridgewater", "Wareham", "Hingham", "Pembroke", "Hanover", "Duxbury", "Marshfield", "Scituate", "Whitman", "Abington", "Halifax", "Kingston", "Rockland", "Norwell", "Carver", "Lakeville", "East Bridgewater", "West Bridgewater", "Hanson", "Hull", "Mattapoisett", "Marion", "Rochester", "Plympton"],
    "Suffolk": ["Boston", "Chelsea", "Revere", "Winthrop"],
    "Worcester": ["Worcester", "Fitchburg", "Leominster", "Shrewsbury", "Westborough", "Northborough", "Southborough", "Grafton", "Millbury", "Auburn", "Oxford", "Webster", "Dudley", "Charlton", "Sturbridge", "Spencer", "Brookfield", "Warren", "Lunenburg", "Lancaster", "Harvard", "Berlin", "Bolton", "Clinton", "West Boylston", "Boylston", "Holden", "Rutland", "Paxton", "Leicester", "Douglas", "Uxbridge", "Northbridge", "Sutton", "Milford", "Hopedale", "Mendon", "Upton", "Blackstone"]
  },
  MI: {
    "Genesee": ["Flint", "Grand Blanc", "Flushing", "Davison", "Clio", "Burton", "Swartz Creek", "Fenton", "Mount Morris", "Linden"],
    "Ingham": ["Lansing", "East Lansing", "Mason", "Holt", "Okemos", "Haslett", "Williamston", "Leslie", "Webberville"],
    "Kalamazoo": ["Kalamazoo", "Portage", "Vicksburg", "Parchment", "Schoolcraft", "Galesburg", "Climax", "Richland"],
    "Kent": ["Grand Rapids", "Wyoming", "Kentwood", "Walker", "Grandville", "East Grand Rapids", "Rockford", "Comstock Park", "Cedar Springs", "Byron Center", "Ada", "Lowell", "Caledonia", "Sparta"],
    "Macomb": ["Warren", "Sterling Heights", "Clinton Township", "Roseville", "St. Clair Shores", "Shelby Township", "Chesterfield", "Mount Clemens", "Fraser", "Harrison Township", "New Baltimore", "Richmond", "Romeo", "Utica"],
    "Marquette": ["Marquette", "Ishpeming", "Negaunee", "Gwinn", "Harvey"],
    "Oakland": ["Troy", "Rochester Hills", "Farmington Hills", "Southfield", "Auburn Hills", "Royal Oak", "Pontiac", "Novi", "West Bloomfield", "Bloomfield Hills", "Birmingham", "Madison Heights", "Oak Park", "Berkley", "Clawson", "Ferndale", "Hazel Park", "Lake Orion", "Milford", "Commerce Township", "Walled Lake", "Wixom", "Waterford", "White Lake", "Orion Township", "Rochester", "Clarkston", "Oxford", "Holly"],
    "Ottawa": ["Holland", "Grand Haven", "Zeeland", "Spring Lake", "Hudsonville", "Allendale", "Coopersville", "Ferrysburg", "Jenison"],
    "Saginaw": ["Saginaw", "Saginaw Township", "Frankenmuth", "Birch Run", "Chesaning", "Hemlock"],
    "Washtenaw": ["Ann Arbor", "Ypsilanti", "Saline", "Dexter", "Chelsea", "Milan", "Manchester", "Pittsfield Township"],
    "Wayne": ["Detroit", "Dearborn", "Livonia", "Westland", "Canton", "Taylor", "Redford", "Romulus", "Inkster", "Garden City", "Wayne", "Hamtramck", "Highland Park", "Allen Park", "Lincoln Park", "Wyandotte", "Trenton", "Southgate", "Riverview", "Flat Rock", "Woodhaven", "Brownstown", "Grosse Pointe", "Plymouth", "Northville", "Belleville"]
  },
  MN: {
    "Anoka": ["Blaine", "Coon Rapids", "Andover", "Anoka", "Fridley", "Columbia Heights", "Spring Lake Park", "Lino Lakes", "Ham Lake", "Ramsey", "East Bethel", "Champlin"],
    "Blue Earth": ["Mankato", "North Mankato", "Eagle Lake", "Lake Crystal", "Mapleton", "Skyline"],
    "Dakota": ["Eagan", "Burnsville", "Lakeville", "Apple Valley", "Farmington", "Rosemount", "Inver Grove Heights", "Hastings", "South St. Paul", "West St. Paul", "Mendota Heights", "Northfield"],
    "Hennepin": ["Minneapolis", "Bloomington", "Plymouth", "Maple Grove", "Brooklyn Park", "Eden Prairie", "Edina", "Minnetonka", "St. Louis Park", "Richfield", "Golden Valley", "Crystal", "New Hope", "Robbinsdale", "Hopkins", "Brooklyn Center", "Champlin", "Rogers", "Wayzata", "Excelsior", "Mound", "Shorewood", "Deephaven", "Long Lake", "Orono", "Medina", "Independence", "Osseo", "Dayton", "Maple Plain"],
    "Olmsted": ["Rochester", "Byron", "Stewartville", "Chatfield", "Pine Island", "Eyota", "Dover", "Oronoco"],
    "Ramsey": ["St. Paul", "Maplewood", "Roseville", "Shoreview", "Arden Hills", "Little Canada", "North St. Paul", "White Bear Lake", "Vadnais Heights", "New Brighton", "Mounds View", "White Bear Township", "Falcon Heights", "Lauderdale"],
    "Scott": ["Shakopee", "Prior Lake", "Savage", "Jordan", "New Prague", "Elko New Market", "Belle Plaine"],
    "St. Louis": ["Duluth", "Hibbing", "Virginia", "Hermantown", "Eveleth", "Mountain Iron", "Proctor", "Cloquet"],
    "Stearns": ["St. Cloud", "Waite Park", "Sartell", "Sauk Rapids", "Cold Spring", "Albany", "Collegeville", "Avon"],
    "Washington": ["Woodbury", "Cottage Grove", "Stillwater", "Forest Lake", "Oakdale", "Lake Elmo", "Hugo", "Mahtomedi", "Scandia", "Bayport", "Afton", "Dellwood"],
    "Wright": ["Buffalo", "Otsego", "Monticello", "St. Michael", "Albertville", "Annandale", "Delano", "Howard Lake"]
  },
  MS: {
    "DeSoto": ["Southaven", "Olive Branch", "Horn Lake", "Hernando", "Walls"],
    "Forrest": ["Hattiesburg", "Petal"],
    "Harrison": ["Gulfport", "Biloxi", "D'Iberville", "Long Beach", "Pass Christian"],
    "Hinds": ["Jackson", "Clinton", "Byram", "Raymond", "Terry", "Bolton", "Edwards", "Utica"],
    "Jackson": ["Ocean Springs", "Pascagoula", "Moss Point", "Gautier", "Vancleave", "Lucedale"],
    "Lamar": ["Hattiesburg", "Lumberton", "Purvis", "Sumrall"],
    "Lauderdale": ["Meridian", "Marion", "Collinsville"],
    "Lee": ["Tupelo", "Saltillo", "Shannon", "Verona", "Baldwyn", "Guntown", "Plantersville", "Nettleton"],
    "Lowndes": ["Columbus", "Caledonia"],
    "Madison": ["Madison", "Canton", "Ridgeland", "Flora", "Gluckstadt"],
    "Rankin": ["Brandon", "Pearl", "Flowood", "Richland", "Pelahatchie"]
  },
  MO: {
    "Boone": ["Columbia", "Ashland", "Centralia", "Hallsville", "Hartsburg"],
    "Buchanan": ["St. Joseph"],
    "Cape Girardeau": ["Cape Girardeau", "Jackson"],
    "Clay": ["Liberty", "Gladstone", "Kearney", "Excelsior Springs", "Smithville", "Lawson", "Holt", "Kansas City"],
    "Cole": ["Jefferson City", "Wardsville", "Russellville"],
    "Greene": ["Springfield", "Republic", "Nixa", "Battlefield", "Strafford", "Rogersville", "Willard", "Ash Grove"],
    "Jackson": ["Kansas City", "Independence", "Lee's Summit", "Blue Springs", "Grandview", "Raytown", "Belton", "Grain Valley", "Raymore", "Greenwood", "Pleasant Hill", "Oak Grove", "Sugar Creek", "Buckner", "Lake Lotawana", "Lone Jack"],
    "Jasper": ["Joplin", "Webb City", "Carthage", "Carl Junction"],
    "Platte": ["Platte City", "Riverside", "Parkville", "Weston", "Camden Point", "Tracy"],
    "St. Charles": ["St. Charles", "O'Fallon", "St. Peters", "Wentzville", "Lake St. Louis", "Dardenne Prairie", "Cottleville", "Weldon Spring"],
    "St. Louis": ["Chesterfield", "Ballwin", "Wildwood", "Florissant", "Hazelwood", "Maryland Heights", "Creve Coeur", "Town and Country", "Kirkwood", "Webster Groves", "Des Peres", "Manchester", "Eureka", "Mehlville", "Concord", "Affton", "Lemay", "Oakville", "Arnold", "Fenton"],
    "St. Louis City": ["St. Louis"]
  },
  MT: {
    "Cascade": ["Great Falls", "Belt", "Neihart"],
    "Flathead": ["Kalispell", "Whitefish", "Columbia Falls", "Bigfork", "Evergreen", "Lakeside"],
    "Gallatin": ["Bozeman", "Belgrade", "Manhattan", "West Yellowstone", "Big Sky", "Three Forks"],
    "Lewis and Clark": ["Helena", "East Helena", "Lincoln", "Wolf Creek"],
    "Missoula": ["Missoula", "Bonner-West Riverside", "Lolo", "Frenchtown", "Clinton", "Seeley Lake"],
    "Yellowstone": ["Billings", "Laurel", "Lockwood", "Shepherd", "Huntley", "Broadview"]
  },
  NE: {
    "Buffalo": ["Kearney", "Gibbon", "Shelton", "Ravenna"],
    "Dakota": ["South Sioux City", "Dakota City", "Homer", "Jackson", "Hubbard"],
    "Douglas": ["Omaha", "Ralston", "Elkhorn", "Bennington", "Valley", "Waterloo", "Boys Town"],
    "Hall": ["Grand Island", "Wood River", "Doniphan", "Alda", "Cairo"],
    "Lancaster": ["Lincoln", "Hickman", "Waverly", "Bennet", "Cortland", "Denton", "Firth", "Malcolm", "Panama", "Roca", "Sprague"],
    "Sarpy": ["Bellevue", "Papillion", "La Vista", "Gretna", "Springfield"]
  },
  NV: {
    "Clark": ["Las Vegas", "Henderson", "North Las Vegas", "Boulder City", "Mesquite", "Laughlin", "Summerlin", "Enterprise", "Spring Valley", "Paradise", "Sunrise Manor", "Whitney"],
    "Washoe": ["Reno", "Sparks", "Sun Valley", "Spanish Springs", "Incline Village", "Verdi", "Mogul", "Lemmon Valley", "Cold Springs"],
    "Carson City": ["Carson City"],
    "Douglas": ["Minden", "Gardnerville", "Stateline", "Topaz Lake", "Johnson Lane", "Indian Hills"],
    "Elko": ["Elko", "Spring Creek", "Carlin", "Wells", "West Wendover"],
    "Lyon": ["Dayton", "Fernley", "Silver Springs", "Yerington"],
    "Nye": ["Pahrump", "Tonopah", "Beatty"]
  },
  NH: {
    "Belknap": ["Laconia", "Gilford", "Meredith", "Tilton", "Belmont", "Barnstead", "Center Harbor", "Alton", "New Hampton", "Sanbornton"],
    "Carroll": ["Wolfeboro", "Conway", "North Conway", "Ossipee", "Tamworth", "Moultonborough", "Jackson", "Bartlett"],
    "Cheshire": ["Keene", "Swanzey", "Jaffrey", "Hinsdale", "Walpole", "Winchester", "Chesterfield", "Marlborough", "Troy"],
    "Grafton": ["Lebanon", "Hanover", "Plymouth", "Littleton", "Bristol", "Canaan", "Enfield", "Haverhill"],
    "Hillsborough": ["Manchester", "Nashua", "Bedford", "Merrimack", "Milford", "Hollis", "Amherst", "Hudson", "Litchfield", "Goffstown", "New Boston", "Brookline", "Mont Vernon", "Lyndeborough", "Wilton", "Peterborough", "Hillsborough", "Antrim", "Bennington", "Deering", "Francestown", "Greenfield", "Greenville", "Hancock", "Mason", "New Ipswich", "Sharon", "Temple", "Weare", "Windsor"],
    "Merrimack": ["Concord", "Pembroke", "Bow", "Hooksett", "Hopkinton", "Warner", "Canterbury", "Loudon", "Epsom", "Bradford", "Salisbury", "Boscawen", "Pittsfield", "Andover", "Danbury", "Franklin", "Henniker", "Northfield", "Hill", "Newbury", "Sutton", "Webster", "Wilmot"],
    "Rockingham": ["Derry", "Salem", "Londonderry", "Windham", "Exeter", "Hampton", "Portsmouth", "Epping", "Raymond", "Plaistow", "Hampstead", "Sandown", "Atkinson", "Chester", "Danville", "East Kingston", "Fremont", "Greenland", "Hampton Falls", "Kensington", "Kingston", "New Castle", "Newfields", "Newington", "Newton", "North Hampton", "Nottingham", "Rye", "Seabrook", "South Hampton", "Stratham"],
    "Strafford": ["Dover", "Rochester", "Somersworth", "Durham", "Barrington", "Rollinsford", "Farmington", "Lee", "Madbury", "Milton", "Middleton", "New Durham", "Strafford"]
  },
  NJ: {
    "Atlantic": ["Atlantic City", "Egg Harbor Township", "Galloway", "Hamilton Township", "Hammonton", "Pleasantville", "Ventnor City", "Absecon", "Brigantine", "Linwood", "Northfield", "Somers Point", "Margate City", "Longport"],
    "Bergen": ["Hackensack", "Fort Lee", "Paramus", "Teaneck", "Bergenfield", "Fair Lawn", "Garfield", "Englewood", "Ridgewood", "Lodi", "Elmwood Park", "Glen Rock", "Lyndhurst", "Rutherford", "North Arlington", "Ramsey", "Mahwah", "Wyckoff", "Saddle River", "Alpine"],
    "Burlington": ["Mount Laurel", "Burlington", "Evesham", "Moorestown", "Medford", "Marlton", "Bordentown", "Cinnaminson", "Delran", "Willingboro", "Palmyra", "Riverside", "Burlington Township", "Florence"],
    "Camden": ["Camden", "Cherry Hill", "Gloucester Township", "Winslow", "Voorhees", "Haddonfield", "Collingswood", "Merchantville", "Pennsauken", "Lindenwold", "Somerdale", "Stratford", "Clementon", "Berlin", "Pine Hill", "Laurel Springs", "Audubon", "Barrington", "Bellmawr", "Brooklawn", "Gibbsboro", "Haddon Heights", "Haddon Township", "Hi-Nella", "Lawnside", "Magnolia", "Mount Ephraim", "Oaklyn", "Runnemede", "Tavistock", "Waterford", "Chesilhurst"],
    "Essex": ["Newark", "East Orange", "Irvington", "Bloomfield", "Montclair", "Orange", "Belleville", "Nutley", "West Orange", "South Orange", "Maplewood", "Livingston", "Millburn", "Caldwell", "West Caldwell", "Cedar Grove", "Verona", "Glen Ridge", "North Caldwell", "Essex Fells", "Roseland", "Fairfield"],
    "Hudson": ["Jersey City", "Hoboken", "Bayonne", "Union City", "North Bergen", "West New York", "Secaucus", "Kearny", "Harrison", "Guttenberg", "Weehawken", "East Newark"],
    "Mercer": ["Trenton", "Princeton", "Hamilton", "Ewing", "Lawrence", "West Windsor", "Hopewell", "Robbinsville", "East Windsor", "Hightstown", "Pennington"],
    "Middlesex": ["New Brunswick", "Edison", "Woodbridge", "Perth Amboy", "Piscataway", "Old Bridge", "East Brunswick", "South Brunswick", "North Brunswick", "Sayreville", "Middlesex", "Metuchen", "Highland Park", "South Plainfield", "South River", "Monroe", "Carteret", "Cranbury", "Plainsboro", "Helmetta", "Jamesburg", "Milltown", "Spotswood", "Dunellen"],
    "Monmouth": ["Freehold", "Long Branch", "Red Bank", "Asbury Park", "Middletown", "Holmdel", "Marlboro", "Manalapan", "Aberdeen", "Matawan", "Tinton Falls", "Ocean Township", "Colts Neck", "Rumson", "Fair Haven", "Little Silver", "Shrewsbury", "Eatontown", "West Long Branch", "Deal", "Allenhurst", "Loch Arbour", "Monmouth Beach", "Sea Bright", "Highlands", "Atlantic Highlands", "Keyport", "Hazlet", "Keansburg", "Union Beach"],
    "Morris": ["Morristown", "Parsippany", "Randolph", "Morris Township", "Denville", "Dover", "Rockaway", "Chester", "Madison", "Chatham", "Florham Park", "Boonton", "Lincoln Park", "Mountain Lakes", "Butler", "Kinnelon", "Long Hill", "Mendham"],
    "Ocean": ["Toms River", "Lakewood", "Brick", "Jackson", "Barnegat", "Berkeley", "Lacey", "Manchester", "Little Egg Harbor", "Ocean Gate", "Stafford", "Point Pleasant", "Point Pleasant Beach", "Beachwood", "Pine Beach", "Island Heights", "Seaside Heights", "Seaside Park", "Lavallette", "Ortley Beach"],
    "Passaic": ["Paterson", "Clifton", "Passaic", "Wayne", "West Milford", "Pompton Lakes", "Wanaque", "Ringwood", "Bloomingdale", "Totowa", "Haledon", "North Haledon", "Prospect Park", "Hawthorne", "Little Falls", "Woodland Park"],
    "Somerset": ["Somerville", "Bridgewater", "Franklin", "Hillsborough", "Warren", "Bernards", "Watchung", "Bedminster", "Bound Brook", "Raritan", "Manville", "North Plainfield", "Green Brook", "Montgomery", "Rocky Hill", "Millstone"],
    "Sussex": ["Newton", "Hopatcong", "Sparta", "Vernon", "Andover", "Stanhope", "Byram", "Franklin", "Hamburg", "Hardyston", "Ogdensburg", "Sussex"],
    "Union": ["Elizabeth", "Union", "Rahway", "Linden", "Plainfield", "Westfield", "Cranford", "Summit", "Scotch Plains", "Fanwood", "Clark", "Kenilworth", "Roselle", "Roselle Park", "Garwood", "Hillside", "Springfield", "New Providence", "Berkeley Heights", "Mountainside", "Winfield"],
    "Warren": ["Phillipsburg", "Hackettstown", "Washington", "Belvidere", "Blairstown", "Oxford", "Alpha", "Lopatcong"]
  },
  NM: {
    "Bernalillo": ["Albuquerque", "Los Ranchos de Albuquerque", "Tijeras", "Cedar Crest"],
    "Dona Ana": ["Las Cruces", "Sunland Park", "Hatch", "Mesilla", "Anthony"],
    "Lea": ["Hobbs", "Lovington", "Eunice", "Jal"],
    "Otero": ["Alamogordo", "Cloudcroft", "Tularosa"],
    "San Juan": ["Farmington", "Aztec", "Bloomfield", "Kirtland"],
    "Sandoval": ["Rio Rancho", "Bernalillo", "Corrales", "Placitas", "Cuba"],
    "Santa Fe": ["Santa Fe", "Eldorado at Santa Fe", "Edgewood", "Pecos"]
  },
  NY: {
    "Albany": ["Albany", "Cohoes", "Colonie", "Watervliet", "Guilderland", "Bethlehem", "Delmar", "Ravena", "Altamont"],
    "Bronx": ["Bronx"],
    "Broome": ["Binghamton", "Johnson City", "Endicott", "Vestal", "Endwell", "Conklin", "Whitney Point", "Kirkwood"],
    "Dutchess": ["Poughkeepsie", "Beacon", "Fishkill", "Wappingers Falls", "Hopewell Junction", "Hyde Park", "Rhinebeck", "Red Hook", "Millbrook", "Dover Plains"],
    "Erie": ["Buffalo", "Cheektowaga", "Amherst", "Tonawanda", "Williamsville", "Hamburg", "Depew", "Lancaster", "Lackawanna", "West Seneca", "Kenmore", "Orchard Park", "East Aurora", "Clarence", "Elma", "Grand Island"],
    "Kings": ["Brooklyn"],
    "Monroe": ["Rochester", "Irondequoit", "Greece", "Gates", "Henrietta", "Webster", "Penfield", "Pittsford", "Brockport", "Fairport", "East Rochester", "Brighton", "Hilton", "Spencerport"],
    "Nassau": ["Hempstead", "Garden City", "Mineola", "Freeport", "Valley Stream", "Lynbrook", "Rockville Centre", "Long Beach", "Glen Cove", "Great Neck", "Manhasset", "Port Washington", "Roslyn", "Oyster Bay", "Massapequa", "Hicksville", "Levittown", "Syosset", "Plainview", "Bethpage", "Farmingdale", "Westbury", "New Hyde Park", "Elmont", "Franklin Square", "Bellmore", "Merrick", "Wantagh", "Seaford", "Floral Park"],
    "New York": ["New York", "Manhattan"],
    "Onondaga": ["Syracuse", "Cicero", "DeWitt", "Manlius", "Camillus", "Clay", "Baldwinsville", "Liverpool", "North Syracuse", "Solvay", "East Syracuse", "Fayetteville", "Minoa", "Skaneateles"],
    "Orange": ["Newburgh", "Middletown", "Monroe", "Warwick", "Cornwall", "Washingtonville", "Goshen", "Chester", "Florida", "Kiryas Joel", "Highland Falls", "Tuxedo Park", "Woodbury"],
    "Queens": ["Queens"],
    "Richmond": ["Staten Island"],
    "Rockland": ["Ramapo", "Clarkstown", "Haverstraw", "Orangetown", "Stony Point", "Spring Valley", "Nanuet", "Suffern", "Pearl River", "New City", "Nyack", "Congers"],
    "Saratoga": ["Saratoga Springs", "Clifton Park", "Halfmoon", "Ballston Spa", "Mechanicville", "Malta", "Stillwater", "Waterford", "Round Lake", "Wilton", "Galway"],
    "Schenectady": ["Schenectady", "Niskayuna", "Rotterdam", "Duanesburg", "Glenville", "Scotia"],
    "Suffolk": ["Babylon", "Brookhaven", "Huntington", "Islip", "Smithtown", "Southold", "Riverhead", "East Hampton", "Southampton", "Shelter Island", "Patchogue", "Bay Shore", "Central Islip", "Commack", "Deer Park", "Dix Hills", "Hauppauge", "Lake Ronkonkoma", "Lindenhurst", "Brentwood", "Copiague", "West Babylon", "Amityville"],
    "Tompkins": ["Ithaca", "Lansing", "Dryden", "Trumansburg", "Groton", "Freeville"],
    "Ulster": ["Kingston", "New Paltz", "Saugerties", "Woodstock", "Ellenville", "Highland", "Rosendale", "Marlboro", "Plattekill"],
    "Westchester": ["Yonkers", "New Rochelle", "Mount Vernon", "White Plains", "Peekskill", "Port Chester", "Scarsdale", "Mamaroneck", "Rye", "Harrison", "Ossining", "Tarrytown", "Dobbs Ferry", "Hastings-on-Hudson", "Bronxville", "Tuckahoe", "Pelham", "Larchmont", "Croton-on-Hudson", "Sleepy Hollow", "Irvington", "Pleasantville", "Cortlandt", "Greenburgh", "Yorktown", "Somers", "Bedford", "Lewisboro", "North Salem", "Pound Ridge", "North Castle", "Mount Kisco", "Armonk", "Chappaqua", "Katonah", "Ardsley", "Elmsford", "Briarcliff Manor"]
  },
  NC: {
    "Buncombe": ["Asheville", "Weaverville", "Black Mountain", "Woodfin", "Montreat", "Biltmore Forest", "Enka"],
    "Cabarrus": ["Concord", "Kannapolis", "Harrisburg", "Mount Pleasant", "Midland"],
    "Catawba": ["Hickory", "Newton", "Conover", "Claremont", "Maiden", "Catawba", "Long View"],
    "Cumberland": ["Fayetteville", "Hope Mills", "Spring Lake", "Stedman", "Eastover"],
    "Durham": ["Durham"],
    "Forsyth": ["Winston-Salem", "Kernersville", "Clemmons", "Lewisville", "Rural Hall", "King", "Tobaccoville", "Walkertown", "Bethania"],
    "Gaston": ["Gastonia", "Mount Holly", "Belmont", "Dallas", "Bessemer City", "Kings Mountain", "Cramerton", "McAdenville", "Lowell", "Ranlo", "Stanley", "Spencer Mountain"],
    "Guilford": ["Greensboro", "High Point", "Jamestown", "Summerfield", "Pleasant Garden", "Sedalia", "Gibsonville", "Stokesdale", "Oak Ridge", "Whitsett"],
    "Iredell": ["Statesville", "Mooresville", "Troutman", "Love Valley"],
    "Johnston": ["Smithfield", "Clayton", "Selma", "Four Oaks", "Benson", "Kenly", "Micro", "Pine Level", "Princeton", "Wilson's Mills", "Archer Lodge"],
    "Mecklenburg": ["Charlotte", "Matthews", "Mint Hill", "Huntersville", "Cornelius", "Davidson", "Pineville", "Stallings", "Indian Trail", "Weddington"],
    "New Hanover": ["Wilmington", "Carolina Beach", "Wrightsville Beach", "Kure Beach", "Leland"],
    "Onslow": ["Jacksonville", "Richlands", "Swansboro", "Sneads Ferry", "Holly Ridge", "North Topsail Beach"],
    "Orange": ["Chapel Hill", "Hillsborough", "Carrboro", "Mebane"],
    "Pitt": ["Greenville", "Winterville", "Farmville", "Ayden", "Bethel", "Grifton"],
    "Rowan": ["Salisbury", "China Grove", "Kannapolis", "East Spencer", "Landis", "Spencer", "Rockwell", "Granite Quarry", "Faith"],
    "Union": ["Monroe", "Indian Trail", "Stallings", "Waxhaw", "Weddington", "Marshville", "Mineral Springs", "Fairview", "Wesley Chapel", "Hemby Bridge"],
    "Wake": ["Raleigh", "Cary", "Apex", "Holly Springs", "Garner", "Fuquay-Varina", "Wake Forest", "Morrisville", "Knightdale", "Wendell", "Zebulon", "Rolesville", "Angier"],
    "Wayne": ["Goldsboro", "Pikeville", "Mount Olive", "Fremont"]
  },
  ND: {
    "Burleigh": ["Bismarck", "Lincoln"],
    "Cass": ["Fargo", "West Fargo", "Horace", "Casselton", "Mapleton", "Kindred"],
    "Grand Forks": ["Grand Forks", "Larimore", "Thompson", "Manvel", "Northwood"],
    "Morton": ["Mandan", "Glen Ullin", "New Salem", "Hebron"],
    "Ward": ["Minot", "Burlington", "Surrey", "Berthold"]
  },
  OH: {
    "Butler": ["Hamilton", "Middletown", "Fairfield", "West Chester", "Liberty Township", "Mason", "Oxford", "Monroe", "Trenton", "Ross"],
    "Clark": ["Springfield", "New Carlisle", "Enon", "South Vienna"],
    "Clermont": ["Milford", "Batavia", "Amelia", "Goshen", "Loveland", "New Richmond", "Williamsburg", "Bethel"],
    "Cuyahoga": ["Cleveland", "Parma", "Lakewood", "Cleveland Heights", "Euclid", "Strongsville", "Westlake", "North Olmsted", "Solon", "Shaker Heights", "North Royalton", "Brunswick", "Broadview Heights", "Brecksville", "Independence", "Beachwood", "Rocky River", "Berea", "Bay Village", "Avon Lake", "Avon", "Olmsted Falls", "Middleburg Heights", "Brook Park", "Garfield Heights"],
    "Delaware": ["Delaware", "Powell", "Westerville", "Sunbury", "Lewis Center", "Galena", "Orange"],
    "Franklin": ["Columbus", "Dublin", "Westerville", "Hilliard", "Grove City", "Reynoldsburg", "Gahanna", "Upper Arlington", "Worthington", "Grandview Heights", "Pickerington", "New Albany", "Canal Winchester", "Bexley", "Whitehall", "Groveport", "Obetz"],
    "Greene": ["Beavercreek", "Xenia", "Fairborn", "Bellbrook", "Yellow Springs", "Cedarville", "Jamestown"],
    "Hamilton": ["Cincinnati", "Norwood", "North College Hill", "Sharonville", "Forest Park", "Blue Ash", "Madeira", "Montgomery", "Indian Hill", "Wyoming", "Deer Park", "Silverton", "Cheviot", "Mount Healthy", "Reading", "Springdale", "Evendale", "Glendale", "Lockland", "Lincoln Heights", "Golf Manor", "Amberley Village", "Mariemont", "Terrace Park", "Newtown"],
    "Lake": ["Mentor", "Lake County", "Painesville", "Willoughby", "Eastlake", "Wickliffe", "Willowick", "Kirtland", "Madison"],
    "Lorain": ["Lorain", "Elyria", "North Ridgeville", "Avon", "Avon Lake", "Oberlin", "Amherst", "Vermilion", "Wellington", "Grafton", "Sheffield Lake", "Sheffield Village", "LaGrange"],
    "Lucas": ["Toledo", "Sylvania", "Maumee", "Oregon", "Perrysburg", "Holland", "Waterville", "Whitehouse"],
    "Mahoning": ["Youngstown", "Boardman", "Canfield", "Poland", "Austintown", "Struthers", "Campbell", "Lowellville", "New Middletown", "Sebring"],
    "Medina": ["Medina", "Wadsworth", "Brunswick", "Hinckley", "Seville", "Lodi", "Litchfield"],
    "Montgomery": ["Dayton", "Kettering", "Centerville", "Huber Heights", "Miamisburg", "Trotwood", "Englewood", "Vandalia", "Oakwood", "West Carrollton", "Moraine", "Clayton", "Germantown", "Brookville"],
    "Stark": ["Canton", "Massillon", "North Canton", "Alliance", "Louisville", "Jackson Township", "Plain Township", "Perry Township", "Lake Township", "Hartville", "Canal Fulton", "Navarre", "Minerva", "Waynesburg", "East Canton"],
    "Summit": ["Akron", "Cuyahoga Falls", "Stow", "Hudson", "Barberton", "Green", "Tallmadge", "Twinsburg", "Munroe Falls", "Silver Lake", "Macedonia", "Northfield", "Norton", "Fairlawn", "Bath", "Copley", "Richfield", "Peninsula"],
    "Warren": ["Mason", "Lebanon", "Franklin", "Springboro", "Waynesville", "Carlisle", "Maineville", "South Lebanon", "Morrow", "Oregonia", "Harveysburg"]
  },
  OK: {
    "Canadian": ["Mustang", "Yukon", "El Reno", "Piedmont", "Union City"],
    "Cleveland": ["Norman", "Moore", "Noble", "Lexington", "Slaughterville"],
    "Comanche": ["Lawton", "Elgin", "Cache", "Fletcher", "Geronimo", "Medicine Park"],
    "Creek": ["Sapulpa", "Bristow", "Drumright", "Kiefer", "Kellyville", "Mannford", "Depew"],
    "Garfield": ["Enid"],
    "Grady": ["Chickasha", "Tuttle", "Blanchard", "Minco", "Rush Springs", "Amber", "Ninnekah", "Alex", "Verden"],
    "Kay": ["Ponca City", "Blackwell", "Newkirk", "Tonkawa"],
    "Muskogee": ["Muskogee", "Fort Gibson", "Webbers Falls", "Haskell"],
    "Oklahoma": ["Oklahoma City", "Midwest City", "Del City", "Edmond", "Choctaw", "The Village", "Nichols Hills", "Spencer", "Valley Brook", "Forest Park", "Smith Village", "Jones", "Harrah", "Luther", "Arcadia"],
    "Payne": ["Stillwater", "Perkins", "Cushing", "Yale", "Glencoe"],
    "Pottawatomie": ["Shawnee", "Tecumseh", "McLoud", "Earlsboro", "Maud"],
    "Rogers": ["Claremore", "Owasso", "Catoosa", "Verdigris", "Chelsea", "Oologah", "Inola", "Foyil"],
    "Tulsa": ["Tulsa", "Broken Arrow", "Jenks", "Bixby", "Sand Springs", "Owasso", "Glenpool", "Collinsville", "Skiatook", "Sperry"],
    "Wagoner": ["Wagoner", "Coweta", "Porter", "Okay", "Redbird"]
  },
  OR: {
    "Benton": ["Corvallis", "Philomath", "Adair Village", "Monroe", "Alsea"],
    "Clackamas": ["Lake Oswego", "Oregon City", "West Linn", "Milwaukie", "Happy Valley", "Gladstone", "Clackamas", "Canby", "Molalla", "Estacada", "Sandy", "Wilsonville", "Tualatin"],
    "Deschutes": ["Bend", "Redmond", "Sisters", "Sunriver", "La Pine"],
    "Douglas": ["Roseburg", "Sutherlin", "Drain", "Reedsport", "Myrtle Creek", "Winston", "Canyonville"],
    "Jackson": ["Medford", "Ashland", "Central Point", "Eagle Point", "Talent", "Phoenix", "Jacksonville", "Rogue River", "Shady Cove", "Gold Hill", "Butte Falls"],
    "Lane": ["Eugene", "Springfield", "Cottage Grove", "Florence", "Junction City", "Veneta", "Creswell", "Coburg", "Lowell", "Oakridge"],
    "Linn": ["Albany", "Lebanon", "Sweet Home", "Harrisburg", "Tangent", "Brownsville", "Millersburg", "Scio", "Halsey"],
    "Marion": ["Salem", "Keizer", "Silverton", "Woodburn", "Stayton", "Aumsville", "Mill City", "Turner", "Sublimity", "Gervais", "Mt. Angel", "Hubbard", "Jefferson", "Scotts Mills", "Gates", "Detroit"],
    "Multnomah": ["Portland", "Gresham", "Troutdale", "Fairview", "Wood Village", "Maywood Park"],
    "Polk": ["Dallas", "Monmouth", "Independence", "Falls City", "West Salem"],
    "Washington": ["Hillsboro", "Beaverton", "Tigard", "Aloha", "Tualatin", "Sherwood", "Forest Grove", "Cornelius", "King City", "Durham", "North Plains", "Banks", "Bethany", "Cedar Hills", "Cedar Mill", "Oak Hills", "Rock Creek"]
  },
  PA: {
    "Allegheny": ["Pittsburgh", "Penn Hills", "Mount Lebanon", "Bethel Park", "Upper St. Clair", "Monroeville", "Ross", "McCandless", "Shaler", "Plum", "Moon", "North Hills", "Baldwin", "Whitehall", "Hampton", "Brentwood", "Dormont", "West Mifflin", "McKeesport", "Carnegie", "Crafton", "Swissvale", "Wilkinsburg", "Forest Hills", "Churchill"],
    "Berks": ["Reading", "Wyomissing", "Muhlenberg", "Spring Township", "Shillington", "Sinking Spring", "West Lawn", "Kutztown", "Fleetwood", "Hamburg", "Birdsboro", "Boyertown"],
    "Bucks": ["Doylestown", "Bensalem", "Bristol", "Levittown", "Langhorne", "Newtown", "Quakertown", "Warminster", "Perkasie", "Yardley", "Morrisville", "Chalfont", "New Hope", "Sellersville", "Telford", "Souderton", "Dublin", "Warrington"],
    "Chester": ["West Chester", "Exton", "Downingtown", "Coatesville", "Phoenixville", "Malvern", "Kennett Square", "Oxford", "Pottstown", "Paoli", "Devon", "Wayne", "Berwyn", "Bryn Mawr"],
    "Cumberland": ["Carlisle", "Mechanicsburg", "Camp Hill", "Shippensburg", "New Cumberland", "Lemoyne", "Wormleysburg", "Enola"],
    "Dauphin": ["Harrisburg", "Hershey", "Hummelstown", "Middletown", "Steelton", "Paxtonia", "Colonial Park", "Lower Paxton", "Swatara"],
    "Delaware": ["Media", "Upper Darby", "Springfield", "Havertown", "Drexel Hill", "Swarthmore", "Lansdowne", "Ridley Park", "Chester", "Marcus Hook", "Broomall", "Marple", "Radnor", "Wayne", "Darby", "Yeadon", "Collingdale", "Folcroft", "Sharon Hill", "Clifton Heights", "Prospect Park", "Glenolden", "Norwood", "Aston"],
    "Erie": ["Erie", "Millcreek", "Fairview", "Edinboro", "North East", "Corry", "Harborcreek", "Girard", "Wesleyville"],
    "Lackawanna": ["Scranton", "Dunmore", "Old Forge", "Moosic", "Taylor", "Clarks Summit", "Carbondale", "Archbald", "Dickson City", "Olyphant", "Blakely", "Jessup", "Throop"],
    "Lancaster": ["Lancaster", "Ephrata", "Lititz", "Elizabethtown", "Manheim", "Columbia", "Mount Joy", "Millersville", "New Holland", "Strasburg", "Quarryville", "Marietta", "Denver"],
    "Lehigh": ["Allentown", "Emmaus", "Macungie", "Whitehall", "South Whitehall", "Upper Macungie", "Lower Macungie", "Salisbury", "Catasauqua", "Coplay", "Coopersburg", "Slatington", "Northampton"],
    "Luzerne": ["Wilkes-Barre", "Hazleton", "Kingston", "Nanticoke", "Pittston", "West Pittston", "Dallas", "Back Mountain", "Mountain Top", "Wyoming", "Edwardsville", "Plains", "Swoyersville", "Forty Fort"],
    "Montgomery": ["Norristown", "King of Prussia", "Lansdale", "Conshohocken", "Pottstown", "Ambler", "Blue Bell", "Plymouth Meeting", "North Wales", "Collegeville", "Hatfield", "Souderton", "Wyndmoor", "Jenkintown", "Cheltenham", "Abington", "Horsham", "Lower Merion", "Upper Merion", "Whitemarsh", "Springfield", "Bryn Mawr", "Ardmore", "Narberth", "Bala Cynwyd", "Haverford"],
    "Northampton": ["Bethlehem", "Easton", "Nazareth", "Bangor", "Northampton", "Bath", "Pen Argyl", "Wind Gap", "Hellertown", "Freemansburg", "Palmer", "Forks", "Wilson", "Tatamy"],
    "Philadelphia": ["Philadelphia"],
    "York": ["York", "Hanover", "Red Lion", "Spring Garden", "Dallastown", "Dover", "Manchester", "East York", "West York", "Jacobus", "Wrightsville", "Shrewsbury", "Glen Rock", "New Freedom", "Stewartstown"]
  },
  RI: {
    "Bristol": ["Bristol", "Barrington", "Warren"],
    "Kent": ["Warwick", "West Warwick", "East Greenwich", "Coventry", "West Greenwich"],
    "Newport": ["Newport", "Middletown", "Portsmouth", "Tiverton", "Jamestown", "Little Compton"],
    "Providence": ["Providence", "Cranston", "Pawtucket", "East Providence", "Woonsocket", "Cumberland", "North Providence", "Johnston", "Lincoln", "Smithfield", "Central Falls", "North Smithfield", "Burrillville", "Glocester", "Scituate", "Foster"],
    "Washington": ["South Kingstown", "Narragansett", "North Kingstown", "Westerly", "Charlestown", "Hopkinton", "Richmond", "Exeter", "West Kingston", "Wakefield"]
  },
  SC: {
    "Aiken": ["Aiken", "North Augusta", "New Ellenton", "Wagener", "Graniteville", "Jackson"],
    "Anderson": ["Anderson", "Pendleton", "Williamston", "Belton", "Honea Path", "Iva", "Pelzer", "Starr"],
    "Beaufort": ["Beaufort", "Hilton Head Island", "Bluffton", "Port Royal", "Hardeeville", "Lady's Island", "Burton"],
    "Berkeley": ["Goose Creek", "Hanahan", "Moncks Corner", "Summerville"],
    "Charleston": ["Charleston", "Mount Pleasant", "North Charleston", "Summerville", "James Island", "Johns Island", "Folly Beach", "Isle of Palms", "Sullivan's Island", "Kiawah Island"],
    "Dorchester": ["Summerville", "Ridgeville", "St. George", "Harleyville", "Reevesville"],
    "Florence": ["Florence", "Lake City", "Johnsonville", "Timmonsville"],
    "Greenville": ["Greenville", "Greer", "Mauldin", "Simpsonville", "Fountain Inn", "Travelers Rest", "Taylors", "Berea", "Parker", "Wade Hampton", "Gantt", "Sans Souci"],
    "Horry": ["Myrtle Beach", "Conway", "North Myrtle Beach", "Surfside Beach", "Loris", "Carolina Forest", "Socastee", "Little River", "Garden City"],
    "Lancaster": ["Lancaster", "Indian Land", "Kershaw", "Heath Springs"],
    "Lexington": ["Lexington", "West Columbia", "Cayce", "Irmo", "Springdale", "South Congaree", "Pine Ridge", "Gilbert", "Batesburg-Leesville", "Chapin", "Gaston", "Pelion", "Swansea"],
    "Pickens": ["Clemson", "Easley", "Pickens", "Central", "Liberty", "Norris", "Six Mile"],
    "Richland": ["Columbia", "Forest Acres", "Arcadia Lakes", "Blythewood", "Eastover", "Hopkins"],
    "Spartanburg": ["Spartanburg", "Boiling Springs", "Inman", "Lyman", "Duncan", "Campobello", "Chesnee", "Cowpens", "Landrum", "Pacolet", "Reidville", "Wellford", "Woodruff"],
    "York": ["Rock Hill", "Fort Mill", "York", "Tega Cay", "Clover", "Lake Wylie", "Riverview"]
  },
  SD: {
    "Brookings": ["Brookings", "Volga", "Aurora", "Bruce"],
    "Brown": ["Aberdeen", "Warner", "Groton", "Hecla", "Frederick"],
    "Codington": ["Watertown", "Florence", "Henry", "Kranzburg"],
    "Lincoln": ["Sioux Falls", "Harrisburg", "Tea", "Canton", "Lennox", "Worthing", "Beresford"],
    "Meade": ["Sturgis", "Piedmont", "Summerset", "Box Elder"],
    "Minnehaha": ["Sioux Falls", "Brandon", "Dell Rapids", "Hartford", "Garretson", "Baltic", "Crooks", "Humboldt", "Valley Springs"],
    "Pennington": ["Rapid City", "Box Elder", "Wall", "Hill City", "Keystone", "New Underwood", "Quinn"]
  },
  TN: {
    "Bradley": ["Cleveland", "Charleston"],
    "Davidson": ["Nashville", "Goodlettsville", "Berry Hill", "Belle Meade", "Forest Hills", "Oak Hill", "Lakewood"],
    "Hamilton": ["Chattanooga", "Signal Mountain", "Soddy-Daisy", "Red Bank", "Collegedale", "East Ridge", "Lookout Mountain"],
    "Knox": ["Knoxville", "Farragut", "Powell", "Halls", "Corryton"],
    "Madison": ["Jackson", "Three Way"],
    "Montgomery": ["Clarksville"],
    "Rutherford": ["Murfreesboro", "Smyrna", "La Vergne", "Eagleville"],
    "Shelby": ["Memphis", "Germantown", "Collierville", "Bartlett", "Lakeland", "Arlington", "Millington"],
    "Sullivan": ["Kingsport", "Bristol", "Bluff City"],
    "Sumner": ["Hendersonville", "Gallatin", "Portland", "White House", "Millersville", "Westmoreland"],
    "Washington": ["Johnson City", "Jonesborough"],
    "Williamson": ["Franklin", "Brentwood", "Nolensville", "Spring Hill", "Fairview", "Thompson's Station"],
    "Wilson": ["Lebanon", "Mount Juliet", "Watertown"]
  },
  TX: {
    "Bell": ["Killeen", "Temple", "Belton", "Harker Heights", "Copperas Cove", "Nolanville", "Salado", "Troy", "Rogers"],
    "Bexar": ["San Antonio", "Converse", "Live Oak", "Universal City", "Schertz", "Windcrest", "Helotes", "Leon Valley", "Shavano Park", "Alamo Heights", "Olmos Park", "Terrell Hills", "Kirby", "China Grove", "Fair Oaks Ranch", "Grey Forest", "Somerset", "Von Ormy"],
    "Brazoria": ["Pearland", "League City", "Alvin", "Angleton", "Lake Jackson", "Clute", "Brazoria", "Freeport", "Manvel", "Surfside Beach", "Richwood", "West Columbia", "Oyster Creek", "Sweeny", "Danbury"],
    "Brazos": ["Bryan", "College Station"],
    "Cameron": ["Brownsville", "Harlingen", "San Benito", "Los Fresnos", "Port Isabel", "South Padre Island", "La Feria", "Combes", "Primera", "Laguna Vista", "Rancho Viejo", "Rio Hondo", "Santa Rosa"],
    "Collin": ["Plano", "McKinney", "Frisco", "Allen", "Wylie", "Murphy", "Sachse", "Anna", "Prosper", "Celina", "Princeton", "Fairview", "Lucas", "Lavon", "Parker", "Melissa", "Farmersville"],
    "Comal": ["New Braunfels", "Garden Ridge", "Bulverde", "Spring Branch", "Canyon Lake"],
    "Dallas": ["Dallas", "Irving", "Garland", "Mesquite", "Grand Prairie", "Richardson", "Carrollton", "Farmers Branch", "DeSoto", "Cedar Hill", "Duncanville", "Lancaster", "Rowlett", "Sachse", "Balch Springs", "Coppell", "Addison", "Highland Park", "University Park", "Cockrell Hill", "Glenn Heights", "Hutchins", "Wilmer", "Seagoville", "Sunnyvale"],
    "Denton": ["Denton", "Lewisville", "Flower Mound", "Little Elm", "The Colony", "Corinth", "Highland Village", "Argyle", "Aubrey", "Cross Roads", "Double Oak", "Copper Canyon", "Hickory Creek", "Lake Dallas", "Pilot Point", "Ponder", "Roanoke", "Sanger", "Trophy Club", "Justin", "Krum", "Northlake", "Oak Point", "Providence Village", "Shady Shores"],
    "Ector": ["Odessa", "Gardendale", "Goldsmith", "West Odessa"],
    "El Paso": ["El Paso", "Socorro", "Horizon City", "Anthony", "Vinton", "Clint", "San Elizario", "Canutillo", "Homestead Meadows", "Fort Bliss"],
    "Fort Bend": ["Sugar Land", "Missouri City", "Rosenberg", "Richmond", "Stafford", "Katy", "Fulshear", "Needville", "Meadows Place", "Simonton", "Thompsons"],
    "Galveston": ["Galveston", "Texas City", "La Marque", "Dickinson", "League City", "Friendswood", "Santa Fe", "Hitchcock", "Jamaica Beach", "Tiki Island"],
    "Guadalupe": ["Seguin", "Schertz", "Cibolo", "New Braunfels", "Marion", "Santa Clara"],
    "Harris": ["Houston", "Pasadena", "Baytown", "Katy", "Pearland", "League City", "Sugar Land", "Spring", "Humble", "Atascocita", "Channelview", "Cypress", "Tomball", "La Porte", "Deer Park", "Bellaire", "West University Place", "Galena Park", "Jacinto City", "Jersey Village", "Hedwig Village", "Hunters Creek Village", "Piney Point Village", "Bunker Hill Village", "Spring Valley Village", "Hilshire Village", "South Houston", "Webster", "Friendswood", "Seabrook", "Shoreacres", "El Lago", "Taylor Lake Village", "Nassau Bay", "Clear Lake"],
    "Hays": ["San Marcos", "Kyle", "Buda", "Wimberley", "Dripping Springs", "Woodcreek", "Uhland"],
    "Hidalgo": ["McAllen", "Edinburg", "Mission", "Pharr", "Weslaco", "Donna", "San Juan", "Alamo", "Mercedes", "Elsa", "Palmview", "Penitas", "La Joya", "Hidalgo", "Palmhurst", "Granjeno", "Sullivan City"],
    "Jefferson": ["Beaumont", "Port Arthur", "Nederland", "Port Neches", "Groves", "Lumberton", "Bevil Oaks", "China", "Nome", "Fannett"],
    "Lubbock": ["Lubbock", "Wolfforth", "Slaton", "Shallowater", "Idalou", "Ransom Canyon", "New Deal", "Abernathy"],
    "McLennan": ["Waco", "Hewitt", "Woodway", "Robinson", "Bellmead", "Lacy-Lakeview", "Beverly Hills", "McGregor", "China Spring", "Lorena", "West"],
    "Midland": ["Midland", "Greenwood"],
    "Montgomery": ["Conroe", "The Woodlands", "Shenandoah", "Oak Ridge North", "Panorama Village", "Willis", "Magnolia", "Montgomery", "Cut and Shoot", "Splendora", "New Caney", "Porter", "Patton Village", "Roman Forest", "Stagecoach", "Woodloch"],
    "Nueces": ["Corpus Christi", "Portland", "Robstown", "Driscoll", "Agua Dulce", "Bishop", "Petronila"],
    "Smith": ["Tyler", "Lindale", "Whitehouse", "Bullard", "Troup", "Arp", "Noonday", "Hideaway"],
    "Tarrant": ["Fort Worth", "Arlington", "North Richland Hills", "Euless", "Bedford", "Hurst", "Grapevine", "Keller", "Southlake", "Colleyville", "Mansfield", "Haltom City", "Watauga", "Richland Hills", "Benbrook", "Crowley", "Forest Hill", "White Settlement", "Saginaw", "Lake Worth", "Westover Hills", "Pantego", "Dalworthington Gardens", "Kennedale", "Burleson", "Azle", "Haslet", "Trophy Club", "Westlake"],
    "Taylor": ["Abilene", "Tye", "Tuscola", "Buffalo Gap", "Merkel"],
    "Tom Green": ["San Angelo", "Wall", "Grape Creek", "Christoval"],
    "Travis": ["Austin", "Round Rock", "Pflugerville", "Cedar Park", "Lago Vista", "Lakeway", "Bee Cave", "Manor", "Rollingwood", "West Lake Hills", "Jonestown", "Volente", "Creedmoor", "Mustang Ridge", "Point Venture"],
    "Webb": ["Laredo"],
    "Wichita": ["Wichita Falls", "Burkburnett", "Iowa Park", "Electra"],
    "Williamson": ["Round Rock", "Georgetown", "Cedar Park", "Leander", "Hutto", "Taylor", "Jarrell", "Liberty Hill", "Coupland", "Florence", "Granger", "Bartlett", "Thrall", "Weir"]
  },
  UT: {
    "Box Elder": ["Brigham City", "Tremonton", "Perry", "Willard", "Bear River City", "Corinne", "Garland", "Honeyville", "Mantua"],
    "Cache": ["Logan", "North Logan", "Hyde Park", "Smithfield", "Providence", "River Heights", "Nibley", "Hyrum", "Wellsville", "Mendon", "Millville", "Richmond"],
    "Davis": ["Bountiful", "Layton", "Clearfield", "Syracuse", "Kaysville", "Centerville", "Farmington", "Fruit Heights", "North Salt Lake", "South Weber", "West Bountiful", "West Point", "Woods Cross", "Clinton", "Sunset"],
    "Iron": ["Cedar City", "Enoch", "Parowan", "Brian Head"],
    "Salt Lake": ["Salt Lake City", "West Valley City", "West Jordan", "Sandy", "South Jordan", "Murray", "Taylorsville", "Draper", "Riverton", "Cottonwood Heights", "Herriman", "Midvale", "Holladay", "South Salt Lake", "Bluffdale", "Millcreek", "Alta", "Brighton"],
    "Summit": ["Park City", "Coalville", "Francis", "Kamas", "Oakley", "Henefer"],
    "Tooele": ["Tooele", "Grantsville", "Stansbury Park", "Erda", "Lake Point"],
    "Utah": ["Provo", "Orem", "Lehi", "Spanish Fork", "Springville", "American Fork", "Eagle Mountain", "Saratoga Springs", "Pleasant Grove", "Lindon", "Highland", "Alpine", "Cedar Hills", "Mapleton", "Salem", "Payson", "Vineyard", "Santaquin", "Elk Ridge", "Woodland Hills", "Genola"],
    "Washington": ["St. George", "Washington", "Hurricane", "Ivins", "Santa Clara", "LaVerkin", "Leeds", "Springdale", "Hildale", "Enterprise", "Toquerville"],
    "Weber": ["Ogden", "Roy", "Riverdale", "South Ogden", "Washington Terrace", "North Ogden", "Pleasant View", "Harrisville", "Farr West", "West Haven", "Hooper", "Plain City", "Huntsville", "Eden"]
  },
  VT: {
    "Addison": ["Middlebury", "Vergennes", "Bristol", "New Haven", "Ferrisburgh", "Monkton", "Cornwall", "Lincoln", "Ripton", "Weybridge", "Starksboro", "Bridport"],
    "Bennington": ["Bennington", "Manchester", "Arlington", "Dorset", "North Bennington", "Old Bennington", "Pownal", "Shaftsbury", "Rupert", "Sandgate", "Sunderland", "Winhall"],
    "Chittenden": ["Burlington", "South Burlington", "Essex", "Essex Junction", "Colchester", "Williston", "Shelburne", "Winooski", "Hinesburg", "Charlotte", "Richmond", "Jericho", "Underhill", "Westford", "Bolton", "Huntington", "Milton", "St. George"],
    "Rutland": ["Rutland", "West Rutland", "Killington", "Castleton", "Fair Haven", "Poultney", "Brandon", "Pittsford", "Proctor", "Wallingford", "Clarendon", "Pawlet", "Wells", "Danby", "Shrewsbury", "Mendon"],
    "Washington": ["Montpelier", "Barre", "Waterbury", "Northfield", "Waitsfield", "Warren", "Berlin", "Middlesex", "Moretown", "Duxbury", "Fayston", "East Montpelier", "Plainfield", "Marshfield", "Williamstown", "Calais"],
    "Windham": ["Brattleboro", "Bellows Falls", "Springfield", "Wilmington", "Putney", "Newfane", "Townshend", "Jamaica", "Londonderry", "Grafton", "Westminster", "Saxtons River", "Chester", "Ludlow", "Weston"],
    "Windsor": ["Hartford", "White River Junction", "Norwich", "Woodstock", "Windsor", "Quechee", "Bethel", "Royalton", "Rochester", "Pomfret", "Sharon", "Barnard", "Bridgewater", "Plymouth", "Reading", "Hartland", "Weathersfield"]
  },
  VA: {
    "Albemarle": ["Charlottesville", "Crozet", "Scottsville", "Earlysville", "North Garden"],
    "Arlington": ["Arlington"],
    "Augusta": ["Staunton", "Waynesboro", "Fishersville", "Stuarts Draft", "Verona", "Fort Defiance", "Mint Spring"],
    "Bedford": ["Bedford", "Forest", "Goode", "Big Island"],
    "Campbell": ["Lynchburg", "Altavista", "Rustburg", "Brookneal"],
    "Chesterfield": ["Midlothian", "Chester", "Colonial Heights", "Moseley", "North Chesterfield", "Bon Air"],
    "Fairfax": ["Fairfax", "Reston", "Herndon", "Vienna", "McLean", "Tysons", "Burke", "Centreville", "Chantilly", "Springfield", "Annandale", "Falls Church", "Lorton", "Clifton", "Great Falls", "Oakton", "Dunn Loring", "Merrifield", "Fair Oaks", "Franconia", "Newington", "Woodbridge"],
    "Frederick": ["Winchester"],
    "Hanover": ["Ashland", "Mechanicsville", "Atlee", "Beaverdam"],
    "Henrico": ["Richmond", "Glen Allen", "Lakeside", "Short Pump", "Innsbrook", "Sandston", "Highland Springs", "Varina"],
    "James City": ["Williamsburg", "Toano", "Norge", "Lightfoot"],
    "Loudoun": ["Leesburg", "Ashburn", "Sterling", "Purcellville", "Hamilton", "Middleburg", "Lovettsville", "Round Hill", "South Riding", "Brambleton", "Broadlands", "Lansdowne", "Aldie"],
    "Montgomery": ["Blacksburg", "Christiansburg", "Radford", "Shawsville", "Elliston"],
    "Prince William": ["Manassas", "Woodbridge", "Dale City", "Lake Ridge", "Dumfries", "Gainesville", "Bristow", "Haymarket", "Occoquan", "Quantico", "Nokesville"],
    "Roanoke": ["Roanoke", "Salem", "Vinton", "Cave Spring", "Hollins"],
    "Rockingham": ["Harrisonburg", "Bridgewater", "Dayton", "Broadway", "Elkton", "Grottoes", "Timberville", "Mount Crawford"],
    "Spotsylvania": ["Fredericksburg", "Spotsylvania Courthouse", "Chancellor", "Massaponax", "Locust Grove"],
    "Stafford": ["Stafford", "Aquia Harbour", "Garrisonville", "Falmouth"],
    "Virginia Beach City": ["Virginia Beach"],
    "York": ["Yorktown", "Poquoson", "Grafton", "Tabb", "Seaford"]
  },
  WA: {
    "Benton": ["Kennewick", "Richland", "West Richland", "Benton City", "Prosser", "Finley"],
    "Chelan": ["Wenatchee", "East Wenatchee", "Leavenworth", "Cashmere", "Chelan"],
    "Clark": ["Vancouver", "Camas", "Washougal", "Battle Ground", "Ridgefield", "La Center", "Salmon Creek", "Hazel Dell", "Orchards", "Minnehaha", "Brush Prairie", "Yacolt"],
    "Franklin": ["Pasco", "Connell", "Mesa", "Kahlotus"],
    "Grant": ["Moses Lake", "Ephrata", "Quincy", "George", "Mattawa", "Royal City", "Soap Lake", "Warden"],
    "Island": ["Oak Harbor", "Langley", "Coupeville", "Clinton", "Freeland", "Greenbank"],
    "King": ["Seattle", "Bellevue", "Kent", "Renton", "Federal Way", "Kirkland", "Auburn", "Redmond", "Sammamish", "Shoreline", "Burien", "Tukwila", "SeaTac", "Mercer Island", "Maple Valley", "Issaquah", "Woodinville", "Bothell", "Kenmore", "Newcastle", "Covington", "Black Diamond", "Enumclaw", "North Bend", "Snoqualmie", "Skykomish", "Duvall", "Carnation", "Fall City", "Vashon"],
    "Kitsap": ["Bremerton", "Silverdale", "Poulsbo", "Bainbridge Island", "Port Orchard", "Kingston"],
    "Pierce": ["Tacoma", "Lakewood", "Puyallup", "University Place", "Bonney Lake", "Gig Harbor", "Spanaway", "Parkland", "Graham", "South Hill", "Steilacoom", "Sumner", "Edgewood", "Fircrest", "Orting", "Buckley", "DuPont", "Milton", "Frederickson", "Elk Plain"],
    "Skagit": ["Mount Vernon", "Burlington", "Sedro-Woolley", "Anacortes", "La Conner", "Concrete"],
    "Snohomish": ["Everett", "Marysville", "Edmonds", "Lynnwood", "Mountlake Terrace", "Lake Stevens", "Mukilteo", "Arlington", "Snohomish", "Monroe", "Mill Creek", "Stanwood", "Granite Falls", "Sultan", "Gold Bar", "Index", "Lake Forest Park", "Kenmore", "Bothell"],
    "Spokane": ["Spokane", "Spokane Valley", "Cheney", "Liberty Lake", "Airway Heights", "Medical Lake", "Deer Park", "Millwood"],
    "Thurston": ["Olympia", "Lacey", "Tumwater", "Yelm", "Rainier", "Tenino", "Bucoda"],
    "Walla Walla": ["Walla Walla", "College Place", "Milton-Freewater", "Waitsburg", "Prescott"],
    "Whatcom": ["Bellingham", "Ferndale", "Lynden", "Blaine", "Sumas", "Everson", "Nooksack"],
    "Yakima": ["Yakima", "Sunnyside", "Selah", "Grandview", "Toppenish", "Wapato", "Zillah", "Union Gap", "Moxee", "Tieton", "Naches", "Granger", "Mabton"]
  },
  WV: {
    "Berkeley": ["Martinsburg", "Hedgesville", "Inwood", "Falling Waters", "Gerrardstown"],
    "Cabell": ["Huntington", "Barboursville", "Milton"],
    "Harrison": ["Clarksburg", "Bridgeport", "Nutter Fort", "Shinnston", "Salem", "Lumberport"],
    "Jefferson": ["Charles Town", "Ranson", "Shepherdstown", "Harpers Ferry", "Bolivar"],
    "Kanawha": ["Charleston", "South Charleston", "St. Albans", "Dunbar", "Nitro", "Cross Lanes", "Sissonville", "Elkview", "Pinch"],
    "Marion": ["Fairmont", "Mannington", "Rivesville", "Farmington", "Barrackville"],
    "Mercer": ["Bluefield", "Princeton", "Athens"],
    "Monongalia": ["Morgantown", "Star City", "Westover", "Granville", "Cheat Lake"],
    "Ohio": ["Wheeling"],
    "Putnam": ["Hurricane", "Winfield", "Eleanor", "Buffalo", "Poca", "Red House"],
    "Raleigh": ["Beckley", "Sophia", "Shady Spring", "Daniel", "Cool Ridge", "Ghent"],
    "Wood": ["Parkersburg", "Vienna", "Williamstown", "Mineral Wells", "Blennerhassett", "Washington"]
  },
  WI: {
    "Brown": ["Green Bay", "De Pere", "Howard", "Suamico", "Ashwaubenon", "Allouez", "Bellevue", "Pulaski", "Denmark", "Wrightstown"],
    "Dane": ["Madison", "Sun Prairie", "Fitchburg", "Middleton", "Verona", "Waunakee", "Stoughton", "Cottage Grove", "Oregon", "McFarland", "DeForest", "Mount Horeb", "Monona", "Maple Bluff", "Shorewood Hills", "Cross Plains", "Black Earth", "Mazomanie", "Blue Mounds", "Deerfield", "Cambridge", "Marshall"],
    "Eau Claire": ["Eau Claire", "Altoona", "Fall Creek", "Augusta"],
    "Fond du Lac": ["Fond du Lac", "Ripon", "North Fond du Lac", "Waupun", "Campbellsport", "Oakfield", "Rosendale"],
    "Kenosha": ["Kenosha", "Pleasant Prairie", "Paddock Lake", "Twin Lakes", "Silver Lake", "Bristol", "Salem Lakes"],
    "La Crosse": ["La Crosse", "Onalaska", "Holmen", "West Salem", "Bangor"],
    "Marathon": ["Wausau", "Weston", "Schofield", "Rothschild", "Rib Mountain", "Kronenwetter", "Mosinee", "Marathon City", "Edgar", "Athens", "Stratford"],
    "Milwaukee": ["Milwaukee", "Wauwatosa", "West Allis", "Greenfield", "South Milwaukee", "Oak Creek", "Franklin", "Cudahy", "St. Francis", "Shorewood", "Whitefish Bay", "Fox Point", "Glendale", "Brown Deer", "River Hills", "Bayside", "Hales Corners", "Greendale", "West Milwaukee"],
    "Outagamie": ["Appleton", "Kaukauna", "Little Chute", "Seymour", "Combined Locks", "Kimberly", "Shiocton", "Black Creek", "Hortonville"],
    "Racine": ["Racine", "Mount Pleasant", "Sturtevant", "Caledonia", "Wind Point", "Elmwood Park", "North Bay", "Burlington", "Waterford", "Rochester", "Union Grove"],
    "Rock": ["Janesville", "Beloit", "Milton", "Edgerton", "Clinton", "Evansville", "Footville", "Orfordville"],
    "Sheboygan": ["Sheboygan", "Sheboygan Falls", "Plymouth", "Kohler", "Elkhart Lake", "Howards Grove", "Cedar Grove", "Oostburg", "Random Lake"],
    "Waukesha": ["Waukesha", "Brookfield", "New Berlin", "Menomonee Falls", "Muskego", "Pewaukee", "Oconomowoc", "Sussex", "Hartland", "Delafield", "Wales", "Dousman", "Elm Grove", "Mukwonago", "Eagle", "North Prairie", "Chenequa", "Nashotah", "Lac La Belle"],
    "Winnebago": ["Oshkosh", "Neenah", "Menasha", "Omro", "Winneconne", "Fox Crossing"]
  },
  WY: {
    "Albany": ["Laramie", "Centennial", "Rock River"],
    "Campbell": ["Gillette", "Wright"],
    "Fremont": ["Lander", "Riverton", "Dubois", "Shoshoni", "Hudson", "Pavillion"],
    "Laramie": ["Cheyenne", "Pine Bluffs", "Burns", "Albin"],
    "Natrona": ["Casper", "Evansville", "Bar Nunn", "Mills", "Midwest", "Edgerton"],
    "Park": ["Cody", "Powell", "Meeteetse", "Wapiti"],
    "Sweetwater": ["Rock Springs", "Green River", "Granger", "Wamsutter"],
    "Teton": ["Jackson", "Wilson", "Moose", "Moran", "Kelly"]
  },
  DC: {
    "District of Columbia": ["Washington"]
  }
};
